/* =====================================================================
   UniMatch — DATA LAYER (expansion pack)
   Pushes ~150 additional universities into window.UM.data.UNIS.
   Must load AFTER data.js and BEFORE engine.js / app.js.
   Same schema as data.js.
   ===================================================================== */
(function (root) {
  const MORE = [
    /* ===== US PUBLIC — Northeast ===== */
    {n:"Binghamton University (SUNY)",loc:"Binghamton, NY",ctry:"USA",region:"Northeast",type:"Public",size:14000,setting:"suburban",net:18000,gpa:3.7,
     strengths:["Business","Engineering","Psychology","Biology","Economics","Computer Science"],v:{collab:.55,quirky:.6,idealist:.55,research:.7,spirit:.55,seminar:.4}},
    {n:"University at Buffalo (SUNY)",loc:"Buffalo, NY",ctry:"USA",region:"Northeast",type:"Public",size:20000,setting:"urban",net:17000,gpa:3.5,
     strengths:["Engineering","Business","Pharmacy","Biology","Computer Science","Architecture"],v:{collab:.5,quirky:.55,idealist:.55,research:.75,spirit:.6,seminar:.3}},
    {n:"University of Vermont",loc:"Burlington, VT",ctry:"USA",region:"Northeast",type:"Public",size:11000,setting:"urban",net:22000,gpa:3.5,
     strengths:["Environmental Science","Business","Nursing","Biology","Psychology","Pre-Med"],v:{collab:.65,quirky:.6,idealist:.8,research:.65,spirit:.6,seminar:.45}},
    {n:"University of New Hampshire",loc:"Durham, NH",ctry:"USA",region:"Northeast",type:"Public",size:12000,setting:"suburban",net:22000,gpa:3.4,
     strengths:["Business","Engineering","Marine Biology","Nursing","Psychology","Hospitality"],v:{collab:.6,quirky:.45,idealist:.55,research:.6,spirit:.7,seminar:.4}},
    {n:"University of Delaware",loc:"Newark, DE",ctry:"USA",region:"Northeast",type:"Public",size:19000,setting:"suburban",net:22000,gpa:3.6,
     strengths:["Chemical Engineering","Business","Nursing","Education","Biology","Fashion"],v:{collab:.55,quirky:.45,idealist:.55,research:.7,spirit:.75,seminar:.35}},
    {n:"Temple University",loc:"Philadelphia, PA",ctry:"USA",region:"Northeast",type:"Public",size:24000,setting:"urban",net:22000,gpa:3.5,
     strengths:["Business","Communications","Engineering","Nursing","Film","Pre-Med"],v:{collab:.55,quirky:.55,idealist:.6,research:.65,spirit:.65,seminar:.3}},
    {n:"New Jersey Institute of Technology",loc:"Newark, NJ",ctry:"USA",region:"Northeast",type:"Public",size:9000,setting:"urban",net:22000,gpa:3.6,
     strengths:["Engineering","Computer Science","Architecture","Data Science","Biomedical Engineering","Physics"],v:{collab:.55,quirky:.6,idealist:.45,research:.7,spirit:.4,seminar:.4}},

    /* ===== US PRIVATE — Northeast ===== */
    {n:"Drexel University",loc:"Philadelphia, PA",ctry:"USA",region:"Northeast",type:"Private",size:15000,setting:"urban",net:32000,gpa:3.6,
     strengths:["Engineering","Business","Computer Science","Nursing","Design","Health Sciences"],v:{collab:.6,quirky:.55,idealist:.5,research:.55,spirit:.4,seminar:.35}},
    {n:"Rochester Institute of Technology",loc:"Rochester, NY",ctry:"USA",region:"Northeast",type:"Private",size:13000,setting:"suburban",net:32000,gpa:3.7,
     strengths:["Engineering","Computer Science","Game Design","Photography","Cybersecurity","Industrial Design"],v:{collab:.65,quirky:.7,idealist:.45,research:.6,spirit:.4,seminar:.45}},
    {n:"Lafayette College",loc:"Easton, PA",ctry:"USA",region:"Northeast",type:"Private",size:2700,setting:"suburban",net:24000,gpa:3.6,
     strengths:["Engineering","Economics","Biology","Government","Psychology","Computer Science"],v:{collab:.8,quirky:.55,idealist:.6,research:.5,spirit:.6,seminar:.9}},
    {n:"Bucknell University",loc:"Lewisburg, PA",ctry:"USA",region:"Northeast",type:"Private",size:3600,setting:"rural",net:35000,gpa:3.6,
     strengths:["Engineering","Business","Biology","Economics","Psychology","Animal Behavior"],v:{collab:.75,quirky:.5,idealist:.55,research:.55,spirit:.7,seminar:.9}},
    {n:"Franklin & Marshall College",loc:"Lancaster, PA",ctry:"USA",region:"Northeast",type:"Private",size:2400,setting:"suburban",net:24000,gpa:3.5,
     strengths:["Government","Business","Biology","Economics","Psychology","Public Health"],v:{collab:.8,quirky:.6,idealist:.65,research:.55,spirit:.5,seminar:.95}},
    {n:"Skidmore College",loc:"Saratoga Springs, NY",ctry:"USA",region:"Northeast",type:"Private",size:2700,setting:"suburban",net:28000,gpa:3.5,
     strengths:["Art","Business","Psychology","Biology","Environmental Studies","English"],v:{collab:.8,quirky:.85,idealist:.75,research:.45,spirit:.4,seminar:.95}},
    {n:"Bard College",loc:"Annandale-on-Hudson, NY",ctry:"USA",region:"Northeast",type:"Private",size:1800,setting:"rural",net:26000,gpa:3.5,
     strengths:["Music","Literature","Film","Politics","Art","Environmental Studies"],v:{collab:.75,quirky:.97,idealist:.95,research:.5,spirit:.15,seminar:.95}},
    {n:"Sarah Lawrence College",loc:"Bronxville, NY",ctry:"USA",region:"Northeast",type:"Private",size:1400,setting:"suburban",net:30000,gpa:3.4,
     strengths:["Creative Writing","Theatre","Literature","Psychology","Film","Visual Art"],v:{collab:.75,quirky:.98,idealist:.9,research:.45,spirit:.1,seminar:.98}},
    {n:"College of the Holy Cross",loc:"Worcester, MA",ctry:"USA",region:"Northeast",type:"Private",size:3100,setting:"suburban",net:26000,gpa:3.6,
     strengths:["Economics","Pre-Med","Political Science","Psychology","English","Biology"],v:{collab:.75,quirky:.5,idealist:.7,research:.5,spirit:.7,seminar:.9}},
    {n:"Providence College",loc:"Providence, RI",ctry:"USA",region:"Northeast",type:"Private",size:4000,setting:"urban",net:30000,gpa:3.5,
     strengths:["Business","Nursing","Political Science","Education","Marketing","Health Sciences"],v:{collab:.65,quirky:.4,idealist:.6,research:.45,spirit:.8,seminar:.7}},
    {n:"Bentley University",loc:"Waltham, MA",ctry:"USA",region:"Northeast",type:"Private",size:4000,setting:"suburban",net:38000,gpa:3.6,
     strengths:["Business","Accounting","Finance","Marketing","Economics","Data Analytics"],v:{collab:.6,quirky:.35,idealist:.35,research:.5,spirit:.55,seminar:.65}},
    {n:"Yeshiva University",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Private",size:2700,setting:"urban",net:30000,gpa:3.5,
     strengths:["Business","Biology","Pre-Med","Psychology","Computer Science","Jewish Studies"],v:{collab:.6,quirky:.6,idealist:.75,research:.55,spirit:.4,seminar:.7}},
    {n:"Pratt Institute",loc:"Brooklyn, NY",ctry:"USA",region:"Northeast",type:"Private",size:3000,setting:"urban",net:38000,gpa:3.5,
     strengths:["Art","Design","Architecture","Illustration","Fashion","Industrial Design"],v:{collab:.6,quirky:.95,idealist:.7,research:.3,spirit:.1,seminar:.85}},
    {n:"The New School (Parsons)",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Private",size:7000,setting:"urban",net:38000,gpa:3.4,
     strengths:["Design","Fashion","Fine Arts","Music","Media Studies","Architecture"],v:{collab:.6,quirky:.95,idealist:.85,research:.35,spirit:.1,seminar:.85}},
    {n:"Olin College of Engineering",loc:"Needham, MA",ctry:"USA",region:"Northeast",type:"Private",size:400,setting:"suburban",net:25000,gpa:3.9,
     strengths:["Engineering","Computer Science","Robotics","Design","Mechanical Engineering","Electrical Engineering"],v:{collab:.95,quirky:.8,idealist:.65,research:.4,spirit:.3,seminar:.98}},
    {n:"Fashion Institute of Technology",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Public",size:8000,setting:"urban",net:18000,gpa:3.4,
     strengths:["Fashion Design","Marketing","Communications","Illustration","Business","Textiles"],v:{collab:.6,quirky:.85,idealist:.55,research:.3,spirit:.15,seminar:.6}},
    {n:"New England Conservatory",loc:"Boston, MA",ctry:"USA",region:"Northeast",type:"Private",size:800,setting:"urban",net:35000,gpa:3.4,
     strengths:["Music","Performance","Composition","Jazz Studies","Conducting","Music Theory"],v:{collab:.6,quirky:.85,idealist:.6,research:.25,spirit:.1,seminar:.9}},

    /* ===== US PUBLIC — South ===== */
    {n:"College of William & Mary",loc:"Williamsburg, VA",ctry:"USA",region:"South",type:"Public",size:6500,setting:"suburban",net:20000,gpa:3.85,
     strengths:["Business","Government","Biology","English","Computer Science","International Relations"],v:{collab:.7,quirky:.7,idealist:.65,research:.65,spirit:.55,seminar:.7}},
    {n:"James Madison University",loc:"Harrisonburg, VA",ctry:"USA",region:"South",type:"Public",size:20000,setting:"suburban",net:18000,gpa:3.6,
     strengths:["Business","Health Sciences","Education","Communications","Nursing","Computer Information Systems"],v:{collab:.6,quirky:.45,idealist:.55,research:.55,spirit:.8,seminar:.4}},
    {n:"George Mason University",loc:"Fairfax, VA",ctry:"USA",region:"South",type:"Public",size:27000,setting:"suburban",net:20000,gpa:3.5,
     strengths:["Computer Science","Business","Economics","Public Policy","Cybersecurity","Criminology"],v:{collab:.5,quirky:.55,idealist:.6,research:.65,spirit:.45,seminar:.3}},
    {n:"Virginia Commonwealth University",loc:"Richmond, VA",ctry:"USA",region:"South",type:"Public",size:22000,setting:"urban",net:18000,gpa:3.4,
     strengths:["Art","Nursing","Business","Engineering","Pharmacy","Mass Communications"],v:{collab:.55,quirky:.7,idealist:.65,research:.65,spirit:.45,seminar:.35}},
    {n:"Louisiana State University",loc:"Baton Rouge, LA",ctry:"USA",region:"South",type:"Public",size:28000,setting:"urban",net:16000,gpa:3.5,
     strengths:["Engineering","Business","Coastal Science","Mass Communication","Petroleum Engineering","Biology"],v:{collab:.55,quirky:.4,idealist:.5,research:.65,spirit:.95,seminar:.25}},
    {n:"University of Kentucky",loc:"Lexington, KY",ctry:"USA",region:"South",type:"Public",size:22000,setting:"urban",net:15000,gpa:3.5,
     strengths:["Business","Engineering","Nursing","Agriculture","Pharmacy","Pre-Med"],v:{collab:.55,quirky:.4,idealist:.5,research:.65,spirit:.9,seminar:.3}},
    {n:"University of Louisville",loc:"Louisville, KY",ctry:"USA",region:"South",type:"Public",size:16000,setting:"urban",net:15000,gpa:3.4,
     strengths:["Business","Engineering","Nursing","Pre-Med","Public Health","Music"],v:{collab:.55,quirky:.45,idealist:.55,research:.65,spirit:.85,seminar:.35}},
    {n:"University of Arkansas",loc:"Fayetteville, AR",ctry:"USA",region:"South",type:"Public",size:24000,setting:"suburban",net:14000,gpa:3.5,
     strengths:["Business","Engineering","Agriculture","Architecture","Supply Chain","Nursing"],v:{collab:.55,quirky:.4,idealist:.5,research:.6,spirit:.9,seminar:.3}},
    {n:"University of Mississippi",loc:"Oxford, MS",ctry:"USA",region:"South",type:"Public",size:18000,setting:"suburban",net:14000,gpa:3.4,
     strengths:["Business","Pharmacy","Accounting","Journalism","Biology","Marketing"],v:{collab:.55,quirky:.4,idealist:.5,research:.55,spirit:.92,seminar:.3}},
    {n:"University of Oklahoma",loc:"Norman, OK",ctry:"USA",region:"South",type:"Public",size:22000,setting:"suburban",net:15000,gpa:3.5,
     strengths:["Engineering","Business","Meteorology","Energy Management","Aviation","Communications"],v:{collab:.55,quirky:.45,idealist:.5,research:.65,spirit:.95,seminar:.3}},
    {n:"Texas Tech University",loc:"Lubbock, TX",ctry:"USA",region:"South",type:"Public",size:33000,setting:"urban",net:15000,gpa:3.5,
     strengths:["Engineering","Business","Agriculture","Architecture","Nursing","Petroleum Engineering"],v:{collab:.55,quirky:.4,idealist:.5,research:.65,spirit:.92,seminar:.25}},
    {n:"University of Houston",loc:"Houston, TX",ctry:"USA",region:"South",type:"Public",size:38000,setting:"urban",net:14000,gpa:3.4,
     strengths:["Engineering","Business","Hospitality","Pharmacy","Computer Science","Petroleum Engineering"],v:{collab:.5,quirky:.5,idealist:.55,research:.65,spirit:.75,seminar:.25}},
    {n:"West Virginia University",loc:"Morgantown, WV",ctry:"USA",region:"South",type:"Public",size:22000,setting:"suburban",net:15000,gpa:3.3,
     strengths:["Engineering","Forensics","Business","Journalism","Nursing","Agriculture"],v:{collab:.55,quirky:.45,idealist:.5,research:.6,spirit:.92,seminar:.3}},
    {n:"University of Central Florida",loc:"Orlando, FL",ctry:"USA",region:"South",type:"Public",size:50000,setting:"urban",net:14000,gpa:3.6,
     strengths:["Engineering","Hospitality","Business","Computer Science","Aerospace","Nursing"],v:{collab:.5,quirky:.5,idealist:.5,research:.65,spirit:.8,seminar:.2}},
    {n:"University of South Florida",loc:"Tampa, FL",ctry:"USA",region:"South",type:"Public",size:38000,setting:"urban",net:13000,gpa:3.6,
     strengths:["Business","Engineering","Public Health","Nursing","Computer Science","Pre-Med"],v:{collab:.5,quirky:.5,idealist:.55,research:.7,spirit:.6,seminar:.25}},
    {n:"Florida International University",loc:"Miami, FL",ctry:"USA",region:"South",type:"Public",size:47000,setting:"urban",net:12000,gpa:3.5,
     strengths:["Business","Hospitality","Engineering","International Relations","Nursing","Computer Science"],v:{collab:.5,quirky:.5,idealist:.6,research:.6,spirit:.6,seminar:.2}},
    {n:"Georgia State University",loc:"Atlanta, GA",ctry:"USA",region:"South",type:"Public",size:27000,setting:"urban",net:14000,gpa:3.4,
     strengths:["Business","Public Health","Computer Science","Policy","Nursing","Film"],v:{collab:.5,quirky:.5,idealist:.65,research:.6,spirit:.5,seminar:.25}},
    {n:"University of Alabama at Birmingham",loc:"Birmingham, AL",ctry:"USA",region:"South",type:"Public",size:14000,setting:"urban",net:15000,gpa:3.6,
     strengths:["Pre-Med","Nursing","Public Health","Engineering","Biology","Dentistry"],v:{collab:.55,quirky:.45,idealist:.6,research:.8,spirit:.55,seminar:.35}},

    /* ===== US PRIVATE — South ===== */
    {n:"Baylor University",loc:"Waco, TX",ctry:"USA",region:"South",type:"Private",size:14000,setting:"urban",net:35000,gpa:3.7,
     strengths:["Business","Engineering","Nursing","Pre-Med","Biology","Education"],v:{collab:.6,quirky:.4,idealist:.65,research:.6,spirit:.9,seminar:.45}},
    {n:"Texas Christian University",loc:"Fort Worth, TX",ctry:"USA",region:"South",type:"Private",size:10000,setting:"urban",net:38000,gpa:3.6,
     strengths:["Business","Nursing","Communications","Education","Engineering","Ranch Management"],v:{collab:.6,quirky:.4,idealist:.55,research:.5,spirit:.88,seminar:.5}},
    {n:"Southern Methodist University",loc:"Dallas, TX",ctry:"USA",region:"South",type:"Private",size:7000,setting:"urban",net:38000,gpa:3.7,
     strengths:["Business","Engineering","Arts","Economics","Computer Science","Communications"],v:{collab:.55,quirky:.45,idealist:.45,research:.55,spirit:.8,seminar:.55}},
    {n:"Sewanee: The University of the South",loc:"Sewanee, TN",ctry:"USA",region:"South",type:"Private",size:1700,setting:"rural",net:24000,gpa:3.5,
     strengths:["English","Biology","Economics","Environmental Studies","History","Political Science"],v:{collab:.78,quirky:.6,idealist:.65,research:.45,spirit:.6,seminar:.95}},
    {n:"Rhodes College",loc:"Memphis, TN",ctry:"USA",region:"South",type:"Private",size:2000,setting:"urban",net:26000,gpa:3.6,
     strengths:["Pre-Med","Business","Biology","Psychology","International Studies","Economics"],v:{collab:.8,quirky:.6,idealist:.75,research:.55,spirit:.5,seminar:.95}},
    {n:"Furman University",loc:"Greenville, SC",ctry:"USA",region:"South",type:"Private",size:2300,setting:"suburban",net:26000,gpa:3.6,
     strengths:["Business","Biology","Political Science","Health Sciences","Chemistry","Sustainability"],v:{collab:.78,quirky:.5,idealist:.65,research:.55,spirit:.6,seminar:.95}},
    {n:"Elon University",loc:"Elon, NC",ctry:"USA",region:"South",type:"Private",size:6000,setting:"suburban",net:30000,gpa:3.5,
     strengths:["Communications","Business","Education","Health Sciences","Computer Science","Marketing"],v:{collab:.7,quirky:.45,idealist:.6,research:.45,spirit:.7,seminar:.6}},
    {n:"Embry-Riddle Aeronautical University",loc:"Daytona Beach, FL",ctry:"USA",region:"South",type:"Private",size:7000,setting:"suburban",net:32000,gpa:3.5,
     strengths:["Aerospace Engineering","Aviation","Cybersecurity","Engineering","Unmanned Systems","Meteorology"],v:{collab:.6,quirky:.55,idealist:.45,research:.6,spirit:.5,seminar:.45}},
    {n:"Savannah College of Art and Design",loc:"Savannah, GA",ctry:"USA",region:"South",type:"Private",size:12000,setting:"urban",net:36000,gpa:3.4,
     strengths:["Animation","Design","Fashion","Film","Illustration","Game Design"],v:{collab:.6,quirky:.9,idealist:.6,research:.3,spirit:.3,seminar:.6}},

    /* ===== US HBCUs ===== */
    {n:"Tuskegee University",loc:"Tuskegee, AL",ctry:"USA",region:"South",type:"Private",size:2800,setting:"rural",net:18000,gpa:3.3,
     strengths:["Engineering","Veterinary Science","Nursing","Architecture","Agriculture","Aerospace Engineering"],v:{collab:.75,quirky:.45,idealist:.85,research:.6,spirit:.75,seminar:.6},flags:["hbcu"]},
    {n:"Tennessee State University",loc:"Nashville, TN",ctry:"USA",region:"South",type:"Public",size:7000,setting:"urban",net:12000,gpa:3.2,
     strengths:["Engineering","Business","Agriculture","Nursing","Computer Science","Music"],v:{collab:.7,quirky:.45,idealist:.8,research:.55,spirit:.9,seminar:.4},flags:["hbcu"]},
    {n:"Prairie View A&M University",loc:"Prairie View, TX",ctry:"USA",region:"South",type:"Public",size:8000,setting:"rural",net:13000,gpa:3.2,
     strengths:["Engineering","Nursing","Business","Architecture","Agriculture","Computer Science"],v:{collab:.72,quirky:.4,idealist:.8,research:.55,spirit:.85,seminar:.4},flags:["hbcu"]},
    {n:"Clark Atlanta University",loc:"Atlanta, GA",ctry:"USA",region:"South",type:"Private",size:3500,setting:"urban",net:20000,gpa:3.2,
     strengths:["Business","Mass Media","Biology","Computer Science","Social Work","Political Science"],v:{collab:.75,quirky:.5,idealist:.88,research:.5,spirit:.8,seminar:.5},flags:["hbcu"]},
    {n:"Morgan State University",loc:"Baltimore, MD",ctry:"USA",region:"South",type:"Public",size:7500,setting:"urban",net:14000,gpa:3.2,
     strengths:["Engineering","Architecture","Business","Computer Science","Nursing","Journalism"],v:{collab:.7,quirky:.45,idealist:.85,research:.6,spirit:.8,seminar:.4},flags:["hbcu"]},
    {n:"Fisk University",loc:"Nashville, TN",ctry:"USA",region:"South",type:"Private",size:1000,setting:"urban",net:18000,gpa:3.3,
     strengths:["Biology","Chemistry","Physics","Music","Psychology","Pre-Med"],v:{collab:.8,quirky:.6,idealist:.9,research:.7,spirit:.6,seminar:.85},flags:["hbcu"]},

    /* ===== US PUBLIC — Midwest ===== */
    {n:"Miami University",loc:"Oxford, OH",ctry:"USA",region:"Midwest",type:"Public",size:17000,setting:"suburban",net:22000,gpa:3.7,
     strengths:["Business","Education","Engineering","Architecture","Marketing","Psychology"],v:{collab:.6,quirky:.45,idealist:.5,research:.6,spirit:.8,seminar:.45}},
    {n:"University of Cincinnati",loc:"Cincinnati, OH",ctry:"USA",region:"Midwest",type:"Public",size:30000,setting:"urban",net:18000,gpa:3.5,
     strengths:["Engineering","Design","Business","Nursing","Architecture","Music"],v:{collab:.6,quirky:.55,idealist:.5,research:.7,spirit:.75,seminar:.3}},
    {n:"Kansas State University",loc:"Manhattan, KS",ctry:"USA",region:"Midwest",type:"Public",size:16000,setting:"suburban",net:14000,gpa:3.4,
     strengths:["Agriculture","Engineering","Architecture","Business","Veterinary Science","Aviation"],v:{collab:.6,quirky:.4,idealist:.5,research:.6,spirit:.9,seminar:.35}},
    {n:"University of Nebraska–Lincoln",loc:"Lincoln, NE",ctry:"USA",region:"Midwest",type:"Public",size:19000,setting:"urban",net:15000,gpa:3.5,
     strengths:["Engineering","Agriculture","Business","Actuarial Science","Journalism","Architecture"],v:{collab:.55,quirky:.45,idealist:.5,research:.65,spirit:.92,seminar:.3}},
    {n:"University of Missouri",loc:"Columbia, MO",ctry:"USA",region:"Midwest",type:"Public",size:23000,setting:"suburban",net:16000,gpa:3.5,
     strengths:["Journalism","Business","Engineering","Agriculture","Nursing","Health Sciences"],v:{collab:.55,quirky:.45,idealist:.55,research:.65,spirit:.88,seminar:.3}},
    {n:"University of Kansas",loc:"Lawrence, KS",ctry:"USA",region:"Midwest",type:"Public",size:19000,setting:"suburban",net:15000,gpa:3.5,
     strengths:["Business","Engineering","Journalism","Pharmacy","Architecture","Aerospace"],v:{collab:.55,quirky:.5,idealist:.55,research:.65,spirit:.9,seminar:.3}},
    {n:"Iowa State University",loc:"Ames, IA",ctry:"USA",region:"Midwest",type:"Public",size:25000,setting:"suburban",net:15000,gpa:3.6,
     strengths:["Engineering","Agriculture","Design","Business","Veterinary Science","Computer Science"],v:{collab:.6,quirky:.45,idealist:.55,research:.7,spirit:.85,seminar:.3}},
    {n:"Missouri University of Science and Technology",loc:"Rolla, MO",ctry:"USA",region:"Midwest",type:"Public",size:6000,setting:"rural",net:16000,gpa:3.6,
     strengths:["Engineering","Computer Science","Mining","Physics","Chemistry","Aerospace"],v:{collab:.6,quirky:.6,idealist:.4,research:.7,spirit:.55,seminar:.45}},

    /* ===== US PRIVATE — Midwest ===== */
    {n:"Marquette University",loc:"Milwaukee, WI",ctry:"USA",region:"Midwest",type:"Private",size:8000,setting:"urban",net:30000,gpa:3.6,
     strengths:["Business","Engineering","Nursing","Communications","Pre-Med","Biomedical Sciences"],v:{collab:.65,quirky:.45,idealist:.7,research:.6,spirit:.75,seminar:.55}},
    {n:"Saint Louis University",loc:"St. Louis, MO",ctry:"USA",region:"Midwest",type:"Private",size:8000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Pre-Med","Aviation","Business","Nursing","Public Health","Biology"],v:{collab:.65,quirky:.45,idealist:.72,research:.65,spirit:.55,seminar:.55}},
    {n:"Loyola University Chicago",loc:"Chicago, IL",ctry:"USA",region:"Midwest",type:"Private",size:12000,setting:"urban",net:30000,gpa:3.6,
     strengths:["Nursing","Business","Pre-Med","Communications","Psychology","Social Work"],v:{collab:.65,quirky:.55,idealist:.78,research:.6,spirit:.5,seminar:.5}},
    {n:"DePaul University",loc:"Chicago, IL",ctry:"USA",region:"Midwest",type:"Private",size:14000,setting:"urban",net:30000,gpa:3.5,
     strengths:["Business","Computer Science","Theatre","Communications","Film","Music"],v:{collab:.6,quirky:.6,idealist:.7,research:.5,spirit:.45,seminar:.45}},
    {n:"Creighton University",loc:"Omaha, NE",ctry:"USA",region:"Midwest",type:"Private",size:4000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Pre-Med","Nursing","Business","Pharmacy","Dentistry","Biology"],v:{collab:.7,quirky:.4,idealist:.72,research:.6,spirit:.65,seminar:.65}},
    {n:"St. Olaf College",loc:"Northfield, MN",ctry:"USA",region:"Midwest",type:"Private",size:3000,setting:"rural",net:22000,gpa:3.6,
     strengths:["Music","Biology","Mathematics","Nursing","Chemistry","Economics"],v:{collab:.8,quirky:.7,idealist:.8,research:.55,spirit:.5,seminar:.9}},
    {n:"Denison University",loc:"Granville, OH",ctry:"USA",region:"Midwest",type:"Private",size:2300,setting:"rural",net:22000,gpa:3.6,
     strengths:["Economics","Biology","Communications","Psychology","Computer Science","Environmental Studies"],v:{collab:.8,quirky:.65,idealist:.7,research:.55,spirit:.5,seminar:.95}},
    {n:"College of Wooster",loc:"Wooster, OH",ctry:"USA",region:"Midwest",type:"Private",size:2000,setting:"suburban",net:24000,gpa:3.5,
     strengths:["Chemistry","Biology","English","Economics","History","Psychology"],v:{collab:.82,quirky:.75,idealist:.75,research:.7,spirit:.45,seminar:.97}},

    /* ===== US PUBLIC — West ===== */
    {n:"University of Utah",loc:"Salt Lake City, UT",ctry:"USA",region:"West",type:"Public",size:25000,setting:"urban",net:14000,gpa:3.6,
     strengths:["Engineering","Business","Computer Science","Film","Pre-Med","Game Design"],v:{collab:.55,quirky:.55,idealist:.55,research:.75,spirit:.7,seminar:.3}},
    {n:"Oregon State University",loc:"Corvallis, OR",ctry:"USA",region:"West",type:"Public",size:26000,setting:"suburban",net:16000,gpa:3.5,
     strengths:["Engineering","Forestry","Oceanography","Agriculture","Computer Science","Pharmacy"],v:{collab:.6,quirky:.5,idealist:.65,research:.7,spirit:.75,seminar:.3}},
    {n:"Washington State University",loc:"Pullman, WA",ctry:"USA",region:"West",type:"Public",size:24000,setting:"rural",net:16000,gpa:3.4,
     strengths:["Engineering","Veterinary Science","Business","Communication","Agriculture","Nursing"],v:{collab:.6,quirky:.45,idealist:.55,research:.65,spirit:.88,seminar:.3}},
    {n:"San Diego State University",loc:"San Diego, CA",ctry:"USA",region:"West",type:"Public",size:31000,setting:"urban",net:16000,gpa:3.6,
     strengths:["Business","Engineering","Nursing","Communications","Computer Science","Public Health"],v:{collab:.55,quirky:.5,idealist:.6,research:.6,spirit:.8,seminar:.25}},
    {n:"California Polytechnic State University, SLO",loc:"San Luis Obispo, CA",ctry:"USA",region:"West",type:"Public",size:21000,setting:"suburban",net:18000,gpa:3.8,
     strengths:["Engineering","Architecture","Agriculture","Business","Computer Science","Industrial Design"],v:{collab:.7,quirky:.5,idealist:.5,research:.45,spirit:.6,seminar:.5}},
    {n:"University of California, Santa Cruz",loc:"Santa Cruz, CA",ctry:"USA",region:"West",type:"Public",size:17000,setting:"suburban",net:17000,gpa:3.7,
     strengths:["Computer Science","Biology","Marine Science","Psychology","Game Design","Environmental Studies"],v:{collab:.6,quirky:.8,idealist:.85,research:.75,spirit:.35,seminar:.3}},
    {n:"University of California, Riverside",loc:"Riverside, CA",ctry:"USA",region:"West",type:"Public",size:22000,setting:"suburban",net:16000,gpa:3.6,
     strengths:["Engineering","Business","Biology","Entomology","Computer Science","Psychology"],v:{collab:.55,quirky:.55,idealist:.7,research:.75,spirit:.5,seminar:.3}},
    {n:"University of New Mexico",loc:"Albuquerque, NM",ctry:"USA",region:"West",type:"Public",size:17000,setting:"urban",net:13000,gpa:3.4,
     strengths:["Engineering","Nursing","Anthropology","Pre-Med","Business","Fine Arts"],v:{collab:.55,quirky:.55,idealist:.65,research:.65,spirit:.6,seminar:.35}},
    {n:"University of Hawaii at Manoa",loc:"Honolulu, HI",ctry:"USA",region:"West",type:"Public",size:13000,setting:"urban",net:16000,gpa:3.5,
     strengths:["Marine Biology","Oceanography","Astronomy","Business","Nursing","Hawaiian Studies"],v:{collab:.6,quirky:.6,idealist:.7,research:.75,spirit:.55,seminar:.35}},

    /* ===== US PRIVATE — West ===== */
    {n:"Gonzaga University",loc:"Spokane, WA",ctry:"USA",region:"West",type:"Private",size:5000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Business","Engineering","Nursing","Pre-Med","Computer Science","Communications"],v:{collab:.7,quirky:.45,idealist:.72,research:.5,spirit:.85,seminar:.6}},
    {n:"University of San Diego",loc:"San Diego, CA",ctry:"USA",region:"West",type:"Private",size:6000,setting:"suburban",net:35000,gpa:3.7,
     strengths:["Business","Engineering","Nursing","International Relations","Computer Science","Marine Science"],v:{collab:.65,quirky:.45,idealist:.7,research:.55,spirit:.6,seminar:.6}},
    {n:"Seattle University",loc:"Seattle, WA",ctry:"USA",region:"West",type:"Private",size:4500,setting:"urban",net:32000,gpa:3.6,
     strengths:["Nursing","Business","Computer Science","Engineering","Pre-Med","Criminal Justice"],v:{collab:.68,quirky:.55,idealist:.8,research:.55,spirit:.4,seminar:.6}},
    {n:"Pepperdine University",loc:"Malibu, CA",ctry:"USA",region:"West",type:"Private",size:3500,setting:"suburban",net:38000,gpa:3.7,
     strengths:["Business","Communications","Political Science","Psychology","Sports Medicine","Religion"],v:{collab:.6,quirky:.4,idealist:.65,research:.5,spirit:.6,seminar:.7}},
    {n:"Chapman University",loc:"Orange, CA",ctry:"USA",region:"West",type:"Private",size:7000,setting:"suburban",net:38000,gpa:3.6,
     strengths:["Film","Business","Communications","Psychology","Computer Science","Music"],v:{collab:.62,quirky:.65,idealist:.6,research:.5,spirit:.5,seminar:.55}},
    {n:"Whitman College",loc:"Walla Walla, WA",ctry:"USA",region:"West",type:"Private",size:1500,setting:"suburban",net:24000,gpa:3.7,
     strengths:["Biology","Economics","Geology","Environmental Studies","Psychology","Politics"],v:{collab:.82,quirky:.65,idealist:.78,research:.55,spirit:.4,seminar:.95}},
    {n:"Occidental College",loc:"Los Angeles, CA",ctry:"USA",region:"West",type:"Private",size:1900,setting:"urban",net:24000,gpa:3.7,
     strengths:["Politics","Biology","Economics","International Relations","Geology","Art"],v:{collab:.8,quirky:.75,idealist:.85,research:.6,spirit:.4,seminar:.95}},
    {n:"Pitzer College",loc:"Claremont, CA",ctry:"USA",region:"West",type:"Private",size:1100,setting:"suburban",net:22000,gpa:3.6,
     strengths:["Environmental Studies","Psychology","Sociology","Media Studies","Political Studies","Art"],v:{collab:.85,quirky:.85,idealist:.95,research:.55,spirit:.3,seminar:.95}},
    {n:"Scripps College",loc:"Claremont, CA",ctry:"USA",region:"West",type:"Private",size:1100,setting:"suburban",net:22000,gpa:3.7,
     strengths:["Art","Biology","Psychology","Economics","English","Politics"],v:{collab:.82,quirky:.8,idealist:.85,research:.6,spirit:.3,seminar:.95},flags:["women"]},
    {n:"Mount Holyoke College",loc:"South Hadley, MA",ctry:"USA",region:"Northeast",type:"Private",size:2200,setting:"rural",net:22000,gpa:3.6,
     strengths:["Biology","Psychology","International Relations","Economics","Environmental Studies","Computer Science"],v:{collab:.82,quirky:.8,idealist:.9,research:.6,spirit:.3,seminar:.95},flags:["women"]},
    {n:"California Institute of the Arts",loc:"Valencia, CA",ctry:"USA",region:"West",type:"Private",size:1000,setting:"suburban",net:38000,gpa:3.3,
     strengths:["Animation","Film","Music","Theatre","Art","Dance"],v:{collab:.65,quirky:.97,idealist:.8,research:.3,spirit:.1,seminar:.9}},
    {n:"School of the Art Institute of Chicago",loc:"Chicago, IL",ctry:"USA",region:"Midwest",type:"Private",size:3500,setting:"urban",net:38000,gpa:3.3,
     strengths:["Art","Design","Film","Photography","Fashion","Architecture"],v:{collab:.6,quirky:.95,idealist:.78,research:.3,spirit:.1,seminar:.85}},

    /* ===== US Service Academies ===== */
    {n:"United States Military Academy (West Point)",loc:"West Point, NY",ctry:"USA",region:"Northeast",type:"Public",size:4400,setting:"suburban",net:0,gpa:3.8,
     strengths:["Engineering","Political Science","Leadership","Computer Science","International Relations","Systems Engineering"],v:{collab:.7,quirky:.3,idealist:.88,research:.55,spirit:.95,seminar:.65}},
    {n:"United States Naval Academy",loc:"Annapolis, MD",ctry:"USA",region:"South",type:"Public",size:4500,setting:"suburban",net:0,gpa:3.8,
     strengths:["Engineering","Naval Science","Political Science","Cyber Operations","Aerospace","Oceanography"],v:{collab:.7,quirky:.3,idealist:.88,research:.55,spirit:.95,seminar:.65}},
    {n:"United States Air Force Academy",loc:"Colorado Springs, CO",ctry:"USA",region:"West",type:"Public",size:4300,setting:"suburban",net:0,gpa:3.8,
     strengths:["Aeronautical Engineering","Engineering","Political Science","Computer Science","Astronautics","Physics"],v:{collab:.7,quirky:.35,idealist:.88,research:.6,spirit:.95,seminar:.6}},

    /* ===== INTERNATIONAL — Canada ===== */
    {n:"Queen's University",loc:"Kingston, ON",ctry:"Canada",region:"International",type:"Public",size:24000,setting:"suburban",net:26000,gpa:3.7,
     strengths:["Business","Engineering","Health Sciences","Computer Science","Economics","Law"],v:{collab:.6,quirky:.5,idealist:.55,research:.75,spirit:.65,seminar:.4}},
    {n:"Western University",loc:"London, ON",ctry:"Canada",region:"International",type:"Public",size:30000,setting:"suburban",net:26000,gpa:3.6,
     strengths:["Business","Medical Sciences","Engineering","Economics","Kinesiology","Computer Science"],v:{collab:.55,quirky:.45,idealist:.5,research:.75,spirit:.6,seminar:.3}},
    {n:"University of Alberta",loc:"Edmonton, AB",ctry:"Canada",region:"International",type:"Public",size:30000,setting:"urban",net:24000,gpa:3.6,
     strengths:["Engineering","Business","Nursing","Petroleum Engineering","Computer Science","Biology"],v:{collab:.5,quirky:.5,idealist:.55,research:.8,spirit:.5,seminar:.3}},
    {n:"McMaster University",loc:"Hamilton, ON",ctry:"Canada",region:"International",type:"Public",size:30000,setting:"suburban",net:26000,gpa:3.7,
     strengths:["Health Sciences","Engineering","Business","Pre-Med","Biology","Computer Science"],v:{collab:.55,quirky:.55,idealist:.6,research:.85,spirit:.5,seminar:.35}},
    {n:"University of Montreal",loc:"Montreal, QC",ctry:"Canada",region:"International",type:"Public",size:36000,setting:"urban",net:22000,gpa:3.6,
     strengths:["Medicine","Business","Law","Computer Science","Psychology","Economics"],v:{collab:.5,quirky:.6,idealist:.65,research:.8,spirit:.4,seminar:.3}},

    /* ===== INTERNATIONAL — UK / Ireland ===== */
    {n:"University of Bristol",loc:"Bristol",ctry:"UK",region:"International",type:"Public",size:22000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Engineering","Medicine","Economics","Law","Computer Science","Physics"],v:{collab:.5,quirky:.6,idealist:.65,research:.85,spirit:.4,seminar:.4}},
    {n:"University of Glasgow",loc:"Glasgow",ctry:"UK",region:"International",type:"Public",size:25000,setting:"urban",net:28000,gpa:3.6,
     strengths:["Medicine","Engineering","Business","Law","Computer Science","Nursing"],v:{collab:.5,quirky:.6,idealist:.65,research:.82,spirit:.4,seminar:.4}},
    {n:"Durham University",loc:"Durham",ctry:"UK",region:"International",type:"Public",size:18000,setting:"suburban",net:30000,gpa:3.7,
     strengths:["Law","Business","Physics","History","Engineering","Geography"],v:{collab:.55,quirky:.65,idealist:.6,research:.85,spirit:.55,seminar:.5}},
    {n:"University of Birmingham",loc:"Birmingham",ctry:"UK",region:"International",type:"Public",size:28000,setting:"urban",net:28000,gpa:3.6,
     strengths:["Business","Engineering","Medicine","Computer Science","Law","Sports Science"],v:{collab:.5,quirky:.55,idealist:.6,research:.8,spirit:.5,seminar:.35}},
    {n:"University of Leeds",loc:"Leeds",ctry:"UK",region:"International",type:"Public",size:32000,setting:"urban",net:28000,gpa:3.5,
     strengths:["Business","Engineering","Medicine","Media","Law","Design"],v:{collab:.5,quirky:.6,idealist:.65,research:.78,spirit:.5,seminar:.35}},
    {n:"University of Bath",loc:"Bath",ctry:"UK",region:"International",type:"Public",size:15000,setting:"suburban",net:30000,gpa:3.6,
     strengths:["Engineering","Business","Architecture","Computer Science","Psychology","Sport Science"],v:{collab:.55,quirky:.55,idealist:.55,research:.78,spirit:.45,seminar:.4}},
    {n:"University College Dublin",loc:"Dublin",ctry:"Ireland",region:"International",type:"Public",size:26000,setting:"suburban",net:26000,gpa:3.6,
     strengths:["Business","Engineering","Agriculture","Medicine","Computer Science","Law"],v:{collab:.55,quirky:.6,idealist:.65,research:.75,spirit:.45,seminar:.4}},

    /* ===== INTERNATIONAL — Continental Europe ===== */
    {n:"EPFL (École Polytechnique Fédérale de Lausanne)",loc:"Lausanne",ctry:"Switzerland",region:"International",type:"Public",size:11000,setting:"urban",net:8000,gpa:3.85,
     strengths:["Engineering","Computer Science","Physics","Robotics","Architecture","Data Science"],v:{collab:.5,quirky:.7,idealist:.55,research:.95,spirit:.3,seminar:.4}},
    {n:"University of Amsterdam",loc:"Amsterdam",ctry:"Netherlands",region:"International",type:"Public",size:30000,setting:"urban",net:15000,gpa:3.6,
     strengths:["Business","Social Sciences","Psychology","Communication","Economics","Law"],v:{collab:.55,quirky:.7,idealist:.75,research:.8,spirit:.3,seminar:.4}},
    {n:"Eindhoven University of Technology",loc:"Eindhoven",ctry:"Netherlands",region:"International",type:"Public",size:13000,setting:"urban",net:15000,gpa:3.7,
     strengths:["Engineering","Computer Science","Data Science","Industrial Design","Robotics","Physics"],v:{collab:.6,quirky:.65,idealist:.55,research:.88,spirit:.3,seminar:.4}},
    {n:"KU Leuven",loc:"Leuven",ctry:"Belgium",region:"International",type:"Public",size:50000,setting:"urban",net:12000,gpa:3.6,
     strengths:["Engineering","Medicine","Biotechnology","Computer Science","Economics","Law"],v:{collab:.5,quirky:.6,idealist:.6,research:.9,spirit:.4,seminar:.35}},
    {n:"Heidelberg University",loc:"Heidelberg",ctry:"Germany",region:"International",type:"Public",size:28000,setting:"urban",net:5000,gpa:3.7,
     strengths:["Medicine","Physics","Law","Biology","Chemistry","Philosophy"],v:{collab:.45,quirky:.7,idealist:.6,research:.92,spirit:.35,seminar:.4}},
    {n:"RWTH Aachen University",loc:"Aachen",ctry:"Germany",region:"International",type:"Public",size:45000,setting:"urban",net:5000,gpa:3.7,
     strengths:["Engineering","Computer Science","Physics","Mechanical Engineering","Data Science","Materials Science"],v:{collab:.5,quirky:.6,idealist:.5,research:.9,spirit:.35,seminar:.3}},
    {n:"Bocconi University",loc:"Milan",ctry:"Italy",region:"International",type:"Private",size:14000,setting:"urban",net:20000,gpa:3.7,
     strengths:["Economics","Finance","Management","Business","Data Science","Law"],v:{collab:.5,quirky:.45,idealist:.4,research:.75,spirit:.35,seminar:.5}},
    {n:"Politecnico di Milano",loc:"Milan",ctry:"Italy",region:"International",type:"Public",size:47000,setting:"urban",net:14000,gpa:3.6,
     strengths:["Engineering","Architecture","Design","Computer Science","Data Science","Aerospace"],v:{collab:.5,quirky:.6,idealist:.5,research:.85,spirit:.35,seminar:.35}},
    {n:"KTH Royal Institute of Technology",loc:"Stockholm",ctry:"Sweden",region:"International",type:"Public",size:14000,setting:"urban",net:10000,gpa:3.6,
     strengths:["Engineering","Computer Science","Architecture","Data Science","Robotics","Physics"],v:{collab:.55,quirky:.6,idealist:.55,research:.88,spirit:.3,seminar:.4}},
    {n:"University of Copenhagen",loc:"Copenhagen",ctry:"Denmark",region:"International",type:"Public",size:28000,setting:"urban",net:10000,gpa:3.6,
     strengths:["Medicine","Biology","Economics","Computer Science","Law","Environmental Science"],v:{collab:.55,quirky:.65,idealist:.7,research:.88,spirit:.3,seminar:.4}},
    {n:"École Polytechnique",loc:"Palaiseau",ctry:"France",region:"International",type:"Public",size:3000,setting:"suburban",net:18000,gpa:3.85,
     strengths:["Engineering","Mathematics","Physics","Computer Science","Economics","Data Science"],v:{collab:.45,quirky:.7,idealist:.5,research:.92,spirit:.45,seminar:.5}},
    {n:"HEC Paris",loc:"Jouy-en-Josas",ctry:"France",region:"International",type:"Private",size:4000,setting:"suburban",net:22000,gpa:3.8,
     strengths:["Business","Management","Finance","Economics","Entrepreneurship","Marketing"],v:{collab:.55,quirky:.45,idealist:.4,research:.7,spirit:.4,seminar:.6}},

    /* ===== INTERNATIONAL — Asia ===== */
    {n:"Peking University",loc:"Beijing",ctry:"China",region:"International",type:"Public",size:16000,setting:"urban",net:10000,gpa:3.95,
     strengths:["Economics","Computer Science","Physics","Law","Business","Mathematics"],v:{collab:.35,quirky:.6,idealist:.5,research:.95,spirit:.4,seminar:.35}},
    {n:"Fudan University",loc:"Shanghai",ctry:"China",region:"International",type:"Public",size:15000,setting:"urban",net:10000,gpa:3.9,
     strengths:["Business","Economics","Medicine","Journalism","Computer Science","International Relations"],v:{collab:.4,quirky:.55,idealist:.5,research:.9,spirit:.4,seminar:.35}},
    {n:"Shanghai Jiao Tong University",loc:"Shanghai",ctry:"China",region:"International",type:"Public",size:16000,setting:"urban",net:10000,gpa:3.9,
     strengths:["Engineering","Medicine","Business","Computer Science","Naval Architecture","Data Science"],v:{collab:.4,quirky:.55,idealist:.45,research:.92,spirit:.4,seminar:.35}},
    {n:"Zhejiang University",loc:"Hangzhou",ctry:"China",region:"International",type:"Public",size:25000,setting:"urban",net:9000,gpa:3.85,
     strengths:["Engineering","Computer Science","Agriculture","Business","Medicine","Data Science"],v:{collab:.4,quirky:.55,idealist:.5,research:.9,spirit:.4,seminar:.3}},
    {n:"Kyoto University",loc:"Kyoto",ctry:"Japan",region:"International",type:"Public",size:13000,setting:"urban",net:12000,gpa:3.85,
     strengths:["Physics","Chemistry","Engineering","Medicine","Biology","Economics"],v:{collab:.4,quirky:.7,idealist:.55,research:.95,spirit:.35,seminar:.4}},
    {n:"Tokyo Institute of Technology",loc:"Tokyo",ctry:"Japan",region:"International",type:"Public",size:5000,setting:"urban",net:12000,gpa:3.85,
     strengths:["Engineering","Computer Science","Physics","Materials Science","Robotics","Chemistry"],v:{collab:.45,quirky:.65,idealist:.5,research:.95,spirit:.3,seminar:.4}},
    {n:"Osaka University",loc:"Osaka",ctry:"Japan",region:"International",type:"Public",size:15000,setting:"urban",net:12000,gpa:3.8,
     strengths:["Engineering","Medicine","Science","Biology","Economics","Robotics"],v:{collab:.45,quirky:.6,idealist:.5,research:.92,spirit:.35,seminar:.4}},
    {n:"Yonsei University",loc:"Seoul",ctry:"South Korea",region:"International",type:"Private",size:26000,setting:"urban",net:14000,gpa:3.8,
     strengths:["Business","Medicine","Engineering","International Studies","Economics","Computer Science"],v:{collab:.4,quirky:.55,idealist:.5,research:.88,spirit:.55,seminar:.35}},
    {n:"Korea University",loc:"Seoul",ctry:"South Korea",region:"International",type:"Private",size:27000,setting:"urban",net:14000,gpa:3.8,
     strengths:["Business","Law","Engineering","Economics","Political Science","Computer Science"],v:{collab:.4,quirky:.5,idealist:.5,research:.85,spirit:.6,seminar:.35}},
    {n:"POSTECH",loc:"Pohang",ctry:"South Korea",region:"International",type:"Private",size:1400,setting:"suburban",net:10000,gpa:3.85,
     strengths:["Engineering","Computer Science","Physics","Materials Science","Chemistry","Data Science"],v:{collab:.55,quirky:.7,idealist:.45,research:.95,spirit:.3,seminar:.45}},
    {n:"Hong Kong University of Science and Technology",loc:"Hong Kong",ctry:"Hong Kong",region:"International",type:"Public",size:10000,setting:"suburban",net:22000,gpa:3.8,
     strengths:["Engineering","Business","Computer Science","Economics","Data Science","Biotechnology"],v:{collab:.45,quirky:.55,idealist:.45,research:.88,spirit:.35,seminar:.35}},
    {n:"Chinese University of Hong Kong",loc:"Hong Kong",ctry:"Hong Kong",region:"International",type:"Public",size:17000,setting:"suburban",net:22000,gpa:3.8,
     strengths:["Business","Medicine","Engineering","Economics","Computer Science","Law"],v:{collab:.45,quirky:.6,idealist:.5,research:.85,spirit:.4,seminar:.35}},
    {n:"National Taiwan University",loc:"Taipei",ctry:"Taiwan",region:"International",type:"Public",size:17000,setting:"urban",net:8000,gpa:3.8,
     strengths:["Engineering","Medicine","Business","Computer Science","Law","Electrical Engineering"],v:{collab:.4,quirky:.55,idealist:.5,research:.9,spirit:.4,seminar:.35}},
    {n:"Indian Institute of Technology Bombay",loc:"Mumbai",ctry:"India",region:"International",type:"Public",size:11000,setting:"urban",net:4000,gpa:3.9,
     strengths:["Engineering","Computer Science","Electrical Engineering","Data Science","Aerospace","Design"],v:{collab:.45,quirky:.65,idealist:.5,research:.9,spirit:.5,seminar:.35}},
    {n:"Indian Institute of Science",loc:"Bangalore",ctry:"India",region:"International",type:"Public",size:4000,setting:"urban",net:4000,gpa:3.9,
     strengths:["Engineering","Physics","Computer Science","Materials Science","Biology","Mathematics"],v:{collab:.5,quirky:.7,idealist:.55,research:.97,spirit:.3,seminar:.45}},

    /* ===== INTERNATIONAL — Oceania ===== */
    {n:"Monash University",loc:"Melbourne",ctry:"Australia",region:"International",type:"Public",size:50000,setting:"suburban",net:28000,gpa:3.6,
     strengths:["Business","Engineering","Medicine","Pharmacy","Computer Science","Law"],v:{collab:.5,quirky:.55,idealist:.65,research:.82,spirit:.45,seminar:.3}},
    {n:"University of Queensland",loc:"Brisbane",ctry:"Australia",region:"International",type:"Public",size:40000,setting:"urban",net:28000,gpa:3.6,
     strengths:["Business","Engineering","Biology","Medicine","Environmental Science","Computer Science"],v:{collab:.5,quirky:.55,idealist:.7,research:.82,spirit:.5,seminar:.3}},
    {n:"UNSW Sydney",loc:"Sydney",ctry:"Australia",region:"International",type:"Public",size:40000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Engineering","Business","Computer Science","Law","Architecture","Data Science"],v:{collab:.5,quirky:.55,idealist:.6,research:.85,spirit:.45,seminar:.3}},
    {n:"University of Auckland",loc:"Auckland",ctry:"New Zealand",region:"International",type:"Public",size:33000,setting:"urban",net:24000,gpa:3.5,
     strengths:["Business","Engineering","Medicine","Computer Science","Law","Architecture"],v:{collab:.55,quirky:.55,idealist:.7,research:.8,spirit:.45,seminar:.3}},

    /* ===== INTERNATIONAL — Middle East ===== */
    {n:"Technion – Israel Institute of Technology",loc:"Haifa",ctry:"Israel",region:"International",type:"Public",size:14000,setting:"urban",net:12000,gpa:3.8,
     strengths:["Engineering","Computer Science","Medicine","Data Science","Aerospace","Physics"],v:{collab:.5,quirky:.65,idealist:.5,research:.92,spirit:.35,seminar:.4}},
    {n:"Tel Aviv University",loc:"Tel Aviv",ctry:"Israel",region:"International",type:"Public",size:30000,setting:"urban",net:14000,gpa:3.7,
     strengths:["Business","Engineering","Computer Science","Law","Medicine","Neuroscience"],v:{collab:.5,quirky:.65,idealist:.6,research:.88,spirit:.4,seminar:.35}}
  ];

  root.UM = root.UM || {};
  root.UM.data = root.UM.data || {};
  if (Array.isArray(root.UM.data.UNIS)) {
    root.UM.data.UNIS.push(...MORE);
  } else {
    root.UM.data.UNIS = MORE;
  }
})(typeof window !== "undefined" ? window : globalThis);
