/* =====================================================================
   UniMatch — DATA LAYER
   Global: window.UM.data
   Vibe dimensions (each 0..1):
     collab   1 = collaborative / low-stress     0 = hyper-competitive
     quirky   1 = quirky-intellectual            0 = work-hard, play-hard
     idealist 1 = idealist / mission-driven      0 = careerist / pre-professional
     research 1 = theory & research heavy        0 = hands-on / project & co-op
     spirit   1 = huge school spirit / athletics 0 = low-key sports scene
     seminar  1 = small seminars / mentorship    0 = large lectures / autonomy
   Figures are approximate public-data estimates; vibe ratings are editorial.
   ===================================================================== */
(function (root) {
  const UNIS = [
    {n:"Massachusetts Institute of Technology",loc:"Cambridge, MA",ctry:"USA",region:"Northeast",type:"Private",size:4600,setting:"urban",net:25000,gpa:3.95,
     strengths:["Engineering","Computer Science","Physics","Math","Economics","Biology"],v:{collab:.7,quirky:.85,idealist:.55,research:.75,spirit:.35,seminar:.55}},
    {n:"Stanford University",loc:"Stanford, CA",ctry:"USA",region:"West",type:"Private",size:7000,setting:"suburban",net:22000,gpa:3.95,
     strengths:["Computer Science","Engineering","Business","Biology","Psychology","Design"],v:{collab:.7,quirky:.6,idealist:.5,research:.6,spirit:.7,seminar:.5}},
    {n:"Harvard University",loc:"Cambridge, MA",ctry:"USA",region:"Northeast",type:"Private",size:7200,setting:"urban",net:18000,gpa:3.95,
     strengths:["Economics","Political Science","Law","Biology","History","Business"],v:{collab:.55,quirky:.55,idealist:.55,research:.75,spirit:.5,seminar:.6}},
    {n:"Yale University",loc:"New Haven, CT",ctry:"USA",region:"Northeast",type:"Private",size:6500,setting:"urban",net:18000,gpa:3.93,
     strengths:["Political Science","History","Drama","English","Biology","Economics"],v:{collab:.75,quirky:.7,idealist:.6,research:.65,spirit:.55,seminar:.75}},
    {n:"Princeton University",loc:"Princeton, NJ",ctry:"USA",region:"Northeast",type:"Private",size:5600,setting:"suburban",net:17000,gpa:3.92,
     strengths:["Math","Physics","Public Policy","Economics","Engineering","Philosophy"],v:{collab:.7,quirky:.65,idealist:.55,research:.85,spirit:.55,seminar:.8}},
    {n:"California Institute of Technology",loc:"Pasadena, CA",ctry:"USA",region:"West",type:"Private",size:1000,setting:"suburban",net:24000,gpa:3.97,
     strengths:["Physics","Engineering","Computer Science","Math","Chemistry","Astronomy"],v:{collab:.8,quirky:.95,idealist:.5,research:.95,spirit:.2,seminar:.85}},
    {n:"University of Chicago",loc:"Chicago, IL",ctry:"USA",region:"Midwest",type:"Private",size:7000,setting:"urban",net:26000,gpa:3.9,
     strengths:["Economics","Math","Political Science","Sociology","Physics","Philosophy"],v:{collab:.45,quirky:.95,idealist:.55,research:.9,spirit:.3,seminar:.75}},
    {n:"Columbia University",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Private",size:8800,setting:"urban",net:23000,gpa:3.91,
     strengths:["Engineering","Political Science","Economics","Journalism","English","Biology"],v:{collab:.5,quirky:.7,idealist:.6,research:.75,spirit:.35,seminar:.7}},
    {n:"University of Pennsylvania",loc:"Philadelphia, PA",ctry:"USA",region:"Northeast",type:"Private",size:10000,setting:"urban",net:24000,gpa:3.9,
     strengths:["Business","Nursing","Economics","Engineering","Biology","Communications"],v:{collab:.5,quirky:.4,idealist:.4,research:.6,spirit:.6,seminar:.55}},
    {n:"Brown University",loc:"Providence, RI",ctry:"USA",region:"Northeast",type:"Private",size:7200,setting:"urban",net:23000,gpa:3.9,
     strengths:["Computer Science","Biology","International Relations","English","Economics","Public Health"],v:{collab:.85,quirky:.85,idealist:.8,research:.55,spirit:.4,seminar:.8}},
    {n:"Dartmouth College",loc:"Hanover, NH",ctry:"USA",region:"Northeast",type:"Private",size:4500,setting:"rural",net:22000,gpa:3.9,
     strengths:["Economics","Government","Engineering","Biology","Computer Science","Environmental Science"],v:{collab:.75,quirky:.5,idealist:.55,research:.5,spirit:.8,seminar:.8}},
    {n:"Cornell University",loc:"Ithaca, NY",ctry:"USA",region:"Northeast",type:"Private",size:15500,setting:"rural",net:30000,gpa:3.9,
     strengths:["Engineering","Agriculture","Hotel Management","Biology","Computer Science","Architecture"],v:{collab:.5,quirky:.6,idealist:.55,research:.7,spirit:.65,seminar:.4}},
    {n:"Duke University",loc:"Durham, NC",ctry:"USA",region:"South",type:"Private",size:6700,setting:"suburban",net:24000,gpa:3.92,
     strengths:["Biology","Public Policy","Engineering","Economics","Computer Science","Pre-Med"],v:{collab:.55,quirky:.45,idealist:.5,research:.7,spirit:.9,seminar:.6}},
    {n:"Northwestern University",loc:"Evanston, IL",ctry:"USA",region:"Midwest",type:"Private",size:8500,setting:"suburban",net:27000,gpa:3.9,
     strengths:["Journalism","Theatre","Engineering","Economics","Communications","Pre-Med"],v:{collab:.6,quirky:.6,idealist:.5,research:.65,spirit:.65,seminar:.6}},
    {n:"Johns Hopkins University",loc:"Baltimore, MD",ctry:"USA",region:"South",type:"Private",size:6000,setting:"urban",net:25000,gpa:3.92,
     strengths:["Biomedical Engineering","Public Health","Biology","Neuroscience","International Relations","Pre-Med"],v:{collab:.4,quirky:.65,idealist:.55,research:.9,spirit:.35,seminar:.6}},
    {n:"Rice University",loc:"Houston, TX",ctry:"USA",region:"South",type:"Private",size:4400,setting:"urban",net:22000,gpa:3.92,
     strengths:["Engineering","Computer Science","Biosciences","Architecture","Economics","Music"],v:{collab:.85,quirky:.7,idealist:.55,research:.7,spirit:.45,seminar:.8}},
    {n:"Vanderbilt University",loc:"Nashville, TN",ctry:"USA",region:"South",type:"Private",size:7100,setting:"urban",net:24000,gpa:3.9,
     strengths:["Education","Engineering","Economics","Music","Biology","Human Development"],v:{collab:.7,quirky:.45,idealist:.55,research:.6,spirit:.75,seminar:.7}},
    {n:"Carnegie Mellon University",loc:"Pittsburgh, PA",ctry:"USA",region:"Northeast",type:"Private",size:7500,setting:"urban",net:33000,gpa:3.88,
     strengths:["Computer Science","Engineering","Drama","Design","Robotics","Business"],v:{collab:.45,quirky:.8,idealist:.4,research:.8,spirit:.3,seminar:.55}},
    {n:"University of California, Berkeley",loc:"Berkeley, CA",ctry:"USA",region:"West",type:"Public",size:32000,setting:"urban",net:18000,gpa:3.89,
     strengths:["Engineering","Computer Science","Economics","Environmental Science","Political Science","Business"],v:{collab:.45,quirky:.8,idealist:.85,research:.85,spirit:.7,seminar:.25}},
    {n:"University of California, Los Angeles",loc:"Los Angeles, CA",ctry:"USA",region:"West",type:"Public",size:32000,setting:"urban",net:17000,gpa:3.9,
     strengths:["Film","Biology","Psychology","Engineering","Economics","Political Science"],v:{collab:.55,quirky:.55,idealist:.65,research:.75,spirit:.85,seminar:.3}},
    {n:"University of Michigan",loc:"Ann Arbor, MI",ctry:"USA",region:"Midwest",type:"Public",size:32000,setting:"suburban",net:20000,gpa:3.88,
     strengths:["Engineering","Business","Computer Science","Political Science","Psychology","Kinesiology"],v:{collab:.55,quirky:.55,idealist:.6,research:.75,spirit:.95,seminar:.3}},
    {n:"University of Texas at Austin",loc:"Austin, TX",ctry:"USA",region:"South",type:"Public",size:40000,setting:"urban",net:17000,gpa:3.8,
     strengths:["Engineering","Computer Science","Business","Communications","Geosciences","Nursing"],v:{collab:.5,quirky:.6,idealist:.55,research:.7,spirit:.95,seminar:.25}},
    {n:"Georgia Institute of Technology",loc:"Atlanta, GA",ctry:"USA",region:"South",type:"Public",size:18000,setting:"urban",net:18000,gpa:3.85,
     strengths:["Engineering","Computer Science","Industrial Design","Business","Architecture","Cybersecurity"],v:{collab:.5,quirky:.6,idealist:.4,research:.7,spirit:.7,seminar:.3}},
    {n:"University of Illinois Urbana-Champaign",loc:"Champaign, IL",ctry:"USA",region:"Midwest",type:"Public",size:35000,setting:"suburban",net:19000,gpa:3.8,
     strengths:["Engineering","Computer Science","Accounting","Agriculture","Psychology","Physics"],v:{collab:.55,quirky:.55,idealist:.5,research:.75,spirit:.8,seminar:.25}},
    {n:"University of Wisconsin–Madison",loc:"Madison, WI",ctry:"USA",region:"Midwest",type:"Public",size:35000,setting:"urban",net:17000,gpa:3.78,
     strengths:["Engineering","Biology","Economics","Communications","Agriculture","Political Science"],v:{collab:.6,quirky:.55,idealist:.65,research:.7,spirit:.85,seminar:.3}},
    {n:"University of North Carolina at Chapel Hill",loc:"Chapel Hill, NC",ctry:"USA",region:"South",type:"Public",size:19000,setting:"suburban",net:14000,gpa:3.8,
     strengths:["Journalism","Biology","Business","Public Health","Political Science","Psychology"],v:{collab:.6,quirky:.5,idealist:.65,research:.65,spirit:.9,seminar:.4}},
    {n:"University of Washington",loc:"Seattle, WA",ctry:"USA",region:"West",type:"Public",size:32000,setting:"urban",net:16000,gpa:3.8,
     strengths:["Computer Science","Engineering","Nursing","Biology","Business","Environmental Science"],v:{collab:.55,quirky:.55,idealist:.7,research:.8,spirit:.7,seminar:.3}},
    {n:"University of Virginia",loc:"Charlottesville, VA",ctry:"USA",region:"South",type:"Public",size:17000,setting:"suburban",net:18000,gpa:3.85,
     strengths:["Business","Economics","Engineering","Political Science","English","Biology"],v:{collab:.6,quirky:.45,idealist:.55,research:.6,spirit:.85,seminar:.45}},
    {n:"New York University",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Private",size:27000,setting:"urban",net:35000,gpa:3.7,
     strengths:["Business","Film","Drama","Economics","Computer Science","Politics"],v:{collab:.5,quirky:.7,idealist:.6,research:.55,spirit:.2,seminar:.35}},
    {n:"University of Southern California",loc:"Los Angeles, CA",ctry:"USA",region:"West",type:"Private",size:21000,setting:"urban",net:32000,gpa:3.82,
     strengths:["Film","Business","Engineering","Communications","Computer Science","Architecture"],v:{collab:.5,quirky:.5,idealist:.4,research:.65,spirit:.9,seminar:.4}},
    {n:"Boston University",loc:"Boston, MA",ctry:"USA",region:"Northeast",type:"Private",size:18000,setting:"urban",net:33000,gpa:3.75,
     strengths:["Business","Communications","Engineering","Biology","International Relations","Health Sciences"],v:{collab:.55,quirky:.55,idealist:.6,research:.65,spirit:.45,seminar:.4}},
    {n:"Tufts University",loc:"Medford, MA",ctry:"USA",region:"Northeast",type:"Private",size:6700,setting:"suburban",net:26000,gpa:3.88,
     strengths:["International Relations","Biology","Engineering","Economics","Political Science","Drama"],v:{collab:.7,quirky:.75,idealist:.8,research:.6,spirit:.4,seminar:.7}},
    {n:"Williams College",loc:"Williamstown, MA",ctry:"USA",region:"Northeast",type:"Private",size:2100,setting:"rural",net:18000,gpa:3.9,
     strengths:["Economics","English","Art History","Biology","Political Science","Math"],v:{collab:.8,quirky:.6,idealist:.6,research:.5,spirit:.6,seminar:.95}},
    {n:"Amherst College",loc:"Amherst, MA",ctry:"USA",region:"Northeast",type:"Private",size:1900,setting:"rural",net:17000,gpa:3.9,
     strengths:["Economics","English","Political Science","Biology","Math","Philosophy"],v:{collab:.8,quirky:.7,idealist:.7,research:.5,spirit:.5,seminar:.95}},
    {n:"Swarthmore College",loc:"Swarthmore, PA",ctry:"USA",region:"Northeast",type:"Private",size:1600,setting:"suburban",net:18000,gpa:3.9,
     strengths:["Engineering","Economics","Biology","Political Science","Computer Science","Philosophy"],v:{collab:.7,quirky:.9,idealist:.85,research:.7,spirit:.25,seminar:.95}},
    {n:"Pomona College",loc:"Claremont, CA",ctry:"USA",region:"West",type:"Private",size:1700,setting:"suburban",net:17000,gpa:3.9,
     strengths:["Economics","Computer Science","Biology","Neuroscience","Math","Politics"],v:{collab:.85,quirky:.75,idealist:.75,research:.55,spirit:.4,seminar:.95}},
    {n:"Harvey Mudd College",loc:"Claremont, CA",ctry:"USA",region:"West",type:"Private",size:900,setting:"suburban",net:30000,gpa:3.92,
     strengths:["Engineering","Computer Science","Physics","Math","Chemistry","Biology"],v:{collab:.9,quirky:.85,idealist:.6,research:.7,spirit:.4,seminar:.95}},
    {n:"Spelman College",loc:"Atlanta, GA",ctry:"USA",region:"South",type:"Private",size:2200,setting:"urban",net:20000,gpa:3.6,
     strengths:["Biology","Psychology","Political Science","Computer Science","Economics","Health Sciences"],v:{collab:.85,quirky:.55,idealist:.9,research:.55,spirit:.65,seminar:.85},flags:["hbcu","women"]},
    {n:"Howard University",loc:"Washington, DC",ctry:"USA",region:"South",type:"Private",size:9500,setting:"urban",net:22000,gpa:3.55,
     strengths:["Political Science","Biology","Business","Journalism","Engineering","Pre-Med"],v:{collab:.7,quirky:.55,idealist:.9,research:.6,spirit:.8,seminar:.5},flags:["hbcu"]},
    {n:"Florida A&M University",loc:"Tallahassee, FL",ctry:"USA",region:"South",type:"Public",size:8500,setting:"urban",net:13000,gpa:3.4,
     strengths:["Business","Engineering","Pharmacy","Journalism","Biology","Agriculture"],v:{collab:.7,quirky:.45,idealist:.8,research:.55,spirit:.9,seminar:.4},flags:["hbcu"]},
    {n:"Wellesley College",loc:"Wellesley, MA",ctry:"USA",region:"Northeast",type:"Private",size:2400,setting:"suburban",net:19000,gpa:3.88,
     strengths:["Economics","Political Science","Biology","Psychology","Computer Science","International Relations"],v:{collab:.8,quirky:.7,idealist:.85,research:.6,spirit:.4,seminar:.95},flags:["women"]},
    {n:"University of Florida",loc:"Gainesville, FL",ctry:"USA",region:"South",type:"Public",size:34000,setting:"suburban",net:12000,gpa:3.8,
     strengths:["Engineering","Business","Biology","Journalism","Agriculture","Pre-Med"],v:{collab:.55,quirky:.45,idealist:.5,research:.7,spirit:.95,seminar:.25}},
    {n:"Arizona State University",loc:"Tempe, AZ",ctry:"USA",region:"West",type:"Public",size:65000,setting:"urban",net:15000,gpa:3.5,
     strengths:["Business","Engineering","Journalism","Computer Science","Sustainability","Design"],v:{collab:.55,quirky:.5,idealist:.6,research:.6,spirit:.85,seminar:.2}},
    {n:"University of Colorado Boulder",loc:"Boulder, CO",ctry:"USA",region:"West",type:"Public",size:30000,setting:"suburban",net:18000,gpa:3.6,
     strengths:["Engineering","Environmental Science","Aerospace","Business","Astrophysics","Geology"],v:{collab:.6,quirky:.55,idealist:.75,research:.7,spirit:.75,seminar:.3}},
    {n:"University of Oxford",loc:"Oxford",ctry:"UK",region:"International",type:"Public",size:12000,setting:"urban",net:40000,gpa:3.9,
     strengths:["Philosophy, Politics & Economics","Law","Medicine","English","Physics","History"],v:{collab:.45,quirky:.8,idealist:.55,research:.9,spirit:.5,seminar:.95}},
    {n:"University of Cambridge",loc:"Cambridge",ctry:"UK",region:"International",type:"Public",size:12000,setting:"urban",net:40000,gpa:3.9,
     strengths:["Math","Engineering","Natural Sciences","Computer Science","Economics","Medicine"],v:{collab:.45,quirky:.8,idealist:.5,research:.92,spirit:.5,seminar:.95}},
    {n:"Imperial College London",loc:"London",ctry:"UK",region:"International",type:"Public",size:11000,setting:"urban",net:38000,gpa:3.88,
     strengths:["Engineering","Medicine","Computer Science","Physics","Business","Math"],v:{collab:.4,quirky:.6,idealist:.45,research:.9,spirit:.3,seminar:.5}},
    {n:"University of Toronto",loc:"Toronto, ON",ctry:"Canada",region:"International",type:"Public",size:60000,setting:"urban",net:30000,gpa:3.8,
     strengths:["Computer Science","Engineering","Business","Biology","Economics","Psychology"],v:{collab:.4,quirky:.65,idealist:.6,research:.85,spirit:.4,seminar:.2}},
    {n:"University of British Columbia",loc:"Vancouver, BC",ctry:"Canada",region:"International",type:"Public",size:46000,setting:"urban",net:28000,gpa:3.75,
     strengths:["Engineering","Agriculture","Business","Computer Science","Environmental Science","Biology"],v:{collab:.55,quirky:.55,idealist:.75,research:.8,spirit:.55,seminar:.25}},
    {n:"McGill University",loc:"Montreal, QC",ctry:"Canada",region:"International",type:"Public",size:27000,setting:"urban",net:25000,gpa:3.78,
     strengths:["Medicine","Engineering","Business","Neuroscience","Economics","Political Science"],v:{collab:.5,quirky:.65,idealist:.65,research:.8,spirit:.45,seminar:.3}},
    {n:"ETH Zurich",loc:"Zurich",ctry:"Switzerland",region:"International",type:"Public",size:14000,setting:"urban",net:8000,gpa:3.85,
     strengths:["Engineering","Computer Science","Physics","Architecture","Math","Environmental Science"],v:{collab:.5,quirky:.7,idealist:.55,research:.95,spirit:.3,seminar:.4}},
    {n:"National University of Singapore",loc:"Singapore",ctry:"Singapore",region:"International",type:"Public",size:30000,setting:"urban",net:18000,gpa:3.85,
     strengths:["Engineering","Computer Science","Business","Medicine","Economics","Data Science"],v:{collab:.45,quirky:.5,idealist:.45,research:.85,spirit:.45,seminar:.3}},
    {n:"University of Melbourne",loc:"Melbourne",ctry:"Australia",region:"International",type:"Public",size:50000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Business","Engineering","Medicine","Law","English","Computer Science"],v:{collab:.55,quirky:.6,idealist:.7,research:.8,spirit:.5,seminar:.3}},
    {n:"Trinity College Dublin",loc:"Dublin",ctry:"Ireland",region:"International",type:"Public",size:18000,setting:"urban",net:26000,gpa:3.7,
     strengths:["English","Computer Science","Business","Law","History","Physics"],v:{collab:.6,quirky:.75,idealist:.7,research:.75,spirit:.5,seminar:.6}},

    /* ---- additional US national privates ---- */
    {n:"Emory University",loc:"Atlanta, GA",ctry:"USA",region:"South",type:"Private",size:7000,setting:"urban",net:28000,gpa:3.85,
     strengths:["Biology","Business","Nursing","Pre-Med","Psychology","Public Health"],v:{collab:.6,quirky:.5,idealist:.6,research:.7,spirit:.45,seminar:.6}},
    {n:"Washington University in St. Louis",loc:"St. Louis, MO",ctry:"USA",region:"Midwest",type:"Private",size:7500,setting:"suburban",net:27000,gpa:3.9,
     strengths:["Pre-Med","Business","Engineering","Biology","Architecture","Psychology"],v:{collab:.65,quirky:.55,idealist:.5,research:.75,spirit:.4,seminar:.65}},
    {n:"University of Notre Dame",loc:"Notre Dame, IN",ctry:"USA",region:"Midwest",type:"Private",size:8800,setting:"suburban",net:27000,gpa:3.9,
     strengths:["Business","Engineering","Political Science","Theology","Economics","Pre-Med"],v:{collab:.7,quirky:.35,idealist:.6,research:.55,spirit:.95,seminar:.6}},
    {n:"Georgetown University",loc:"Washington, DC",ctry:"USA",region:"South",type:"Private",size:7500,setting:"urban",net:28000,gpa:3.9,
     strengths:["International Relations","Political Science","Business","Economics","Law","Pre-Med"],v:{collab:.5,quirky:.5,idealist:.65,research:.65,spirit:.6,seminar:.6}},
    {n:"Boston College",loc:"Chestnut Hill, MA",ctry:"USA",region:"Northeast",type:"Private",size:9500,setting:"suburban",net:30000,gpa:3.85,
     strengths:["Business","Nursing","Communications","Economics","Biology","Political Science"],v:{collab:.6,quirky:.4,idealist:.6,research:.6,spirit:.75,seminar:.55}},
    {n:"Tulane University",loc:"New Orleans, LA",ctry:"USA",region:"South",type:"Private",size:8000,setting:"urban",net:35000,gpa:3.8,
     strengths:["Public Health","Business","Architecture","Biology","Political Science","Neuroscience"],v:{collab:.6,quirky:.6,idealist:.7,research:.6,spirit:.7,seminar:.5}},
    {n:"Wake Forest University",loc:"Winston-Salem, NC",ctry:"USA",region:"South",type:"Private",size:5400,setting:"suburban",net:30000,gpa:3.85,
     strengths:["Business","Biology","Communications","Political Science","Economics","Pre-Med"],v:{collab:.55,quirky:.45,idealist:.55,research:.6,spirit:.7,seminar:.75}},
    {n:"Case Western Reserve University",loc:"Cleveland, OH",ctry:"USA",region:"Midwest",type:"Private",size:6000,setting:"urban",net:33000,gpa:3.85,
     strengths:["Engineering","Pre-Med","Nursing","Biology","Computer Science","Biomedical Engineering"],v:{collab:.55,quirky:.7,idealist:.5,research:.8,spirit:.35,seminar:.55}},
    {n:"Rensselaer Polytechnic Institute",loc:"Troy, NY",ctry:"USA",region:"Northeast",type:"Private",size:6000,setting:"suburban",net:38000,gpa:3.85,
     strengths:["Engineering","Computer Science","Architecture","Physics","Game Design","Robotics"],v:{collab:.5,quirky:.7,idealist:.4,research:.75,spirit:.45,seminar:.5}},
    {n:"Worcester Polytechnic Institute",loc:"Worcester, MA",ctry:"USA",region:"Northeast",type:"Private",size:4800,setting:"urban",net:38000,gpa:3.8,
     strengths:["Engineering","Robotics","Computer Science","Biomedical Engineering","Physics","Data Science"],v:{collab:.85,quirky:.65,idealist:.55,research:.45,spirit:.4,seminar:.7}},
    {n:"University of Rochester",loc:"Rochester, NY",ctry:"USA",region:"Northeast",type:"Private",size:6500,setting:"suburban",net:32000,gpa:3.8,
     strengths:["Optics","Music","Pre-Med","Engineering","Economics","Biology"],v:{collab:.65,quirky:.7,idealist:.55,research:.8,spirit:.35,seminar:.65}},
    {n:"Brandeis University",loc:"Waltham, MA",ctry:"USA",region:"Northeast",type:"Private",size:3600,setting:"suburban",net:28000,gpa:3.8,
     strengths:["Biology","Economics","Computer Science","Political Science","Psychology","International Relations"],v:{collab:.7,quirky:.8,idealist:.8,research:.7,spirit:.3,seminar:.8}},
    {n:"University of Miami",loc:"Coral Gables, FL",ctry:"USA",region:"South",type:"Private",size:12000,setting:"suburban",net:35000,gpa:3.7,
     strengths:["Marine Science","Business","Communications","Music","Biology","Engineering"],v:{collab:.55,quirky:.45,idealist:.5,research:.6,spirit:.8,seminar:.45}},
    {n:"Northeastern University",loc:"Boston, MA",ctry:"USA",region:"Northeast",type:"Private",size:16000,setting:"urban",net:35000,gpa:3.85,
     strengths:["Business","Engineering","Computer Science","Health Sciences","Data Science","Criminology"],v:{collab:.55,quirky:.55,idealist:.5,research:.55,spirit:.4,seminar:.35}},
    {n:"George Washington University",loc:"Washington, DC",ctry:"USA",region:"South",type:"Private",size:11000,setting:"urban",net:35000,gpa:3.7,
     strengths:["Political Science","International Relations","Business","Public Health","Communications","Economics"],v:{collab:.5,quirky:.5,idealist:.7,research:.6,spirit:.4,seminar:.45}},
    {n:"Villanova University",loc:"Villanova, PA",ctry:"USA",region:"Northeast",type:"Private",size:6900,setting:"suburban",net:35000,gpa:3.8,
     strengths:["Business","Nursing","Engineering","Communications","Biology","Computer Science"],v:{collab:.6,quirky:.4,idealist:.6,research:.55,spirit:.85,seminar:.6}},
    {n:"Syracuse University",loc:"Syracuse, NY",ctry:"USA",region:"Northeast",type:"Private",size:15000,setting:"urban",net:35000,gpa:3.6,
     strengths:["Communications","Architecture","Business","Sport Management","Engineering","Information Studies"],v:{collab:.55,quirky:.5,idealist:.5,research:.55,spirit:.85,seminar:.4}},
    {n:"Santa Clara University",loc:"Santa Clara, CA",ctry:"USA",region:"West",type:"Private",size:6000,setting:"suburban",net:38000,gpa:3.75,
     strengths:["Engineering","Business","Computer Science","Economics","Communications","Pre-Med"],v:{collab:.6,quirky:.45,idealist:.6,research:.55,spirit:.55,seminar:.6}},
    {n:"Babson College",loc:"Wellesley, MA",ctry:"USA",region:"Northeast",type:"Private",size:2500,setting:"suburban",net:38000,gpa:3.7,
     strengths:["Business","Entrepreneurship","Finance","Economics","Marketing","Data Science"],v:{collab:.7,quirky:.4,idealist:.4,research:.4,spirit:.5,seminar:.75}},

    /* ---- liberal arts colleges ---- */
    {n:"Middlebury College",loc:"Middlebury, VT",ctry:"USA",region:"Northeast",type:"Private",size:2600,setting:"rural",net:19000,gpa:3.85,
     strengths:["Languages","Environmental Science","International Relations","English","Economics","Political Science"],v:{collab:.8,quirky:.6,idealist:.75,research:.5,spirit:.55,seminar:.95}},
    {n:"Bowdoin College",loc:"Brunswick, ME",ctry:"USA",region:"Northeast",type:"Private",size:1900,setting:"suburban",net:18000,gpa:3.88,
     strengths:["Government","Biology","Economics","Environmental Science","English","Computer Science"],v:{collab:.85,quirky:.6,idealist:.7,research:.5,spirit:.5,seminar:.95}},
    {n:"Carleton College",loc:"Northfield, MN",ctry:"USA",region:"Midwest",type:"Private",size:2000,setting:"rural",net:20000,gpa:3.85,
     strengths:["Computer Science","Biology","Economics","Physics","Political Science","English"],v:{collab:.85,quirky:.8,idealist:.7,research:.6,spirit:.4,seminar:.95}},
    {n:"Davidson College",loc:"Davidson, NC",ctry:"USA",region:"South",type:"Private",size:1900,setting:"suburban",net:19000,gpa:3.85,
     strengths:["Biology","Economics","Political Science","English","Pre-Med","Psychology"],v:{collab:.8,quirky:.5,idealist:.65,research:.5,spirit:.65,seminar:.95}},
    {n:"Colby College",loc:"Waterville, ME",ctry:"USA",region:"Northeast",type:"Private",size:2200,setting:"rural",net:19000,gpa:3.85,
     strengths:["Environmental Science","Economics","Biology","Government","Computer Science","English"],v:{collab:.8,quirky:.6,idealist:.7,research:.55,spirit:.5,seminar:.95}},
    {n:"Hamilton College",loc:"Clinton, NY",ctry:"USA",region:"Northeast",type:"Private",size:2000,setting:"rural",net:20000,gpa:3.8,
     strengths:["Economics","Government","English","Biology","Mathematics","Psychology"],v:{collab:.8,quirky:.6,idealist:.6,research:.5,spirit:.5,seminar:.95}},
    {n:"Vassar College",loc:"Poughkeepsie, NY",ctry:"USA",region:"Northeast",type:"Private",size:2400,setting:"suburban",net:22000,gpa:3.8,
     strengths:["English","Drama","Art History","Biology","Political Science","Film"],v:{collab:.8,quirky:.9,idealist:.85,research:.5,spirit:.3,seminar:.95}},
    {n:"Wesleyan University",loc:"Middletown, CT",ctry:"USA",region:"Northeast",type:"Private",size:3000,setting:"suburban",net:23000,gpa:3.8,
     strengths:["Film","English","Government","Economics","Biology","Music"],v:{collab:.75,quirky:.9,idealist:.9,research:.6,spirit:.35,seminar:.9}},
    {n:"Grinnell College",loc:"Grinnell, IA",ctry:"USA",region:"Midwest",type:"Private",size:1700,setting:"rural",net:18000,gpa:3.8,
     strengths:["Computer Science","Economics","Biology","Political Science","English","Mathematics"],v:{collab:.85,quirky:.85,idealist:.9,research:.6,spirit:.3,seminar:.95}},
    {n:"Oberlin College",loc:"Oberlin, OH",ctry:"USA",region:"Midwest",type:"Private",size:2900,setting:"suburban",net:24000,gpa:3.6,
     strengths:["Music","Biology","English","Environmental Science","Politics","Chemistry"],v:{collab:.8,quirky:.95,idealist:.95,research:.55,spirit:.25,seminar:.9}},
    {n:"Reed College",loc:"Portland, OR",ctry:"USA",region:"West",type:"Private",size:1400,setting:"urban",net:28000,gpa:3.75,
     strengths:["Biology","Chemistry","English","Physics","Psychology","Philosophy"],v:{collab:.7,quirky:.98,idealist:.85,research:.85,spirit:.15,seminar:.95}},
    {n:"Macalester College",loc:"St. Paul, MN",ctry:"USA",region:"Midwest",type:"Private",size:2200,setting:"urban",net:22000,gpa:3.8,
     strengths:["International Relations","Economics","Biology","Political Science","Environmental Science","Computer Science"],v:{collab:.8,quirky:.75,idealist:.9,research:.55,spirit:.35,seminar:.95}},
    {n:"Claremont McKenna College",loc:"Claremont, CA",ctry:"USA",region:"West",type:"Private",size:1400,setting:"suburban",net:22000,gpa:3.88,
     strengths:["Economics","Government","Finance","International Relations","Psychology","Data Science"],v:{collab:.7,quirky:.5,idealist:.45,research:.55,spirit:.55,seminar:.95}},
    {n:"Haverford College",loc:"Haverford, PA",ctry:"USA",region:"Northeast",type:"Private",size:1400,setting:"suburban",net:24000,gpa:3.85,
     strengths:["Biology","Computer Science","English","Physics","Political Science","Psychology"],v:{collab:.85,quirky:.8,idealist:.85,research:.65,spirit:.3,seminar:.95}},
    {n:"Colorado College",loc:"Colorado Springs, CO",ctry:"USA",region:"West",type:"Private",size:2000,setting:"suburban",net:28000,gpa:3.75,
     strengths:["Environmental Science","Geology","Economics","Biology","Political Science","Art"],v:{collab:.8,quirky:.7,idealist:.8,research:.5,spirit:.45,seminar:.95}},
    {n:"Kenyon College",loc:"Gambier, OH",ctry:"USA",region:"Midwest",type:"Private",size:1800,setting:"rural",net:28000,gpa:3.75,
     strengths:["English","Drama","Biology","Political Science","History","Psychology"],v:{collab:.8,quirky:.8,idealist:.75,research:.45,spirit:.4,seminar:.95}},
    {n:"Barnard College",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Private",size:2700,setting:"urban",net:24000,gpa:3.85,
     strengths:["English","Economics","Psychology","Political Science","Biology","Art History"],v:{collab:.75,quirky:.75,idealist:.85,research:.6,spirit:.3,seminar:.9},flags:["women"]},
    {n:"Smith College",loc:"Northampton, MA",ctry:"USA",region:"Northeast",type:"Private",size:2500,setting:"suburban",net:22000,gpa:3.7,
     strengths:["Engineering","Government","Biology","Psychology","English","Economics"],v:{collab:.8,quirky:.8,idealist:.9,research:.6,spirit:.3,seminar:.95},flags:["women"]},
    {n:"Bryn Mawr College",loc:"Bryn Mawr, PA",ctry:"USA",region:"Northeast",type:"Private",size:1400,setting:"suburban",net:25000,gpa:3.7,
     strengths:["Biology","Mathematics","Psychology","Chemistry","English","Computer Science"],v:{collab:.8,quirky:.85,idealist:.85,research:.7,spirit:.25,seminar:.95},flags:["women"]},

    /* ---- flagship & large public universities ---- */
    {n:"University of California, San Diego",loc:"La Jolla, CA",ctry:"USA",region:"West",type:"Public",size:33000,setting:"suburban",net:17000,gpa:3.85,
     strengths:["Biology","Engineering","Computer Science","Cognitive Science","Economics","Oceanography"],v:{collab:.5,quirky:.65,idealist:.6,research:.85,spirit:.45,seminar:.25}},
    {n:"University of California, Davis",loc:"Davis, CA",ctry:"USA",region:"West",type:"Public",size:31000,setting:"suburban",net:17000,gpa:3.8,
     strengths:["Agriculture","Veterinary Science","Environmental Science","Biology","Engineering","Viticulture"],v:{collab:.6,quirky:.55,idealist:.75,research:.8,spirit:.55,seminar:.3}},
    {n:"University of California, Irvine",loc:"Irvine, CA",ctry:"USA",region:"West",type:"Public",size:30000,setting:"suburban",net:16000,gpa:3.8,
     strengths:["Computer Science","Biology","Business","Engineering","Psychology","Public Health"],v:{collab:.55,quirky:.55,idealist:.6,research:.75,spirit:.55,seminar:.3}},
    {n:"University of California, Santa Barbara",loc:"Santa Barbara, CA",ctry:"USA",region:"West",type:"Public",size:23000,setting:"suburban",net:17000,gpa:3.8,
     strengths:["Physics","Engineering","Environmental Science","Economics","Biology","Marine Science"],v:{collab:.55,quirky:.6,idealist:.65,research:.8,spirit:.7,seminar:.3}},
    {n:"University of Maryland",loc:"College Park, MD",ctry:"USA",region:"South",type:"Public",size:30000,setting:"suburban",net:18000,gpa:3.8,
     strengths:["Computer Science","Engineering","Business","Criminology","Public Health","Journalism"],v:{collab:.55,quirky:.55,idealist:.6,research:.75,spirit:.85,seminar:.3}},
    {n:"Ohio State University",loc:"Columbus, OH",ctry:"USA",region:"Midwest",type:"Public",size:46000,setting:"urban",net:18000,gpa:3.7,
     strengths:["Business","Engineering","Biology","Psychology","Agriculture","Computer Science"],v:{collab:.5,quirky:.45,idealist:.5,research:.7,spirit:.97,seminar:.2}},
    {n:"Pennsylvania State University",loc:"University Park, PA",ctry:"USA",region:"Northeast",type:"Public",size:40000,setting:"suburban",net:25000,gpa:3.6,
     strengths:["Engineering","Business","Communications","Agriculture","Computer Science","Kinesiology"],v:{collab:.5,quirky:.45,idealist:.5,research:.7,spirit:.97,seminar:.25}},
    {n:"Purdue University",loc:"West Lafayette, IN",ctry:"USA",region:"Midwest",type:"Public",size:35000,setting:"suburban",net:16000,gpa:3.7,
     strengths:["Engineering","Computer Science","Aviation","Agriculture","Business","Pharmacy"],v:{collab:.55,quirky:.55,idealist:.45,research:.75,spirit:.85,seminar:.3}},
    {n:"University of Minnesota",loc:"Minneapolis, MN",ctry:"USA",region:"Midwest",type:"Public",size:35000,setting:"urban",net:17000,gpa:3.7,
     strengths:["Engineering","Business","Biology","Psychology","Computer Science","Journalism"],v:{collab:.55,quirky:.55,idealist:.6,research:.75,spirit:.8,seminar:.3}},
    {n:"Indiana University Bloomington",loc:"Bloomington, IN",ctry:"USA",region:"Midwest",type:"Public",size:33000,setting:"suburban",net:16000,gpa:3.6,
     strengths:["Business","Music","Public Affairs","Biology","Informatics","Journalism"],v:{collab:.55,quirky:.55,idealist:.55,research:.65,spirit:.9,seminar:.3}},
    {n:"Michigan State University",loc:"East Lansing, MI",ctry:"USA",region:"Midwest",type:"Public",size:38000,setting:"suburban",net:17000,gpa:3.6,
     strengths:["Business","Education","Agriculture","Engineering","Communications","Supply Chain"],v:{collab:.55,quirky:.45,idealist:.55,research:.7,spirit:.9,seminar:.25}},
    {n:"Rutgers University",loc:"New Brunswick, NJ",ctry:"USA",region:"Northeast",type:"Public",size:36000,setting:"suburban",net:18000,gpa:3.7,
     strengths:["Business","Engineering","Pharmacy","Computer Science","Biology","Psychology"],v:{collab:.5,quirky:.55,idealist:.6,research:.75,spirit:.7,seminar:.25}},
    {n:"University of Pittsburgh",loc:"Pittsburgh, PA",ctry:"USA",region:"Northeast",type:"Public",size:19000,setting:"urban",net:22000,gpa:3.75,
     strengths:["Nursing","Pharmacy","Pre-Med","Engineering","Biology","Computer Science"],v:{collab:.55,quirky:.55,idealist:.6,research:.8,spirit:.7,seminar:.35}},
    {n:"University of Georgia",loc:"Athens, GA",ctry:"USA",region:"South",type:"Public",size:30000,setting:"suburban",net:14000,gpa:3.8,
     strengths:["Business","Journalism","Biology","Agriculture","Political Science","Pharmacy"],v:{collab:.55,quirky:.4,idealist:.5,research:.65,spirit:.95,seminar:.3}},
    {n:"University of Alabama",loc:"Tuscaloosa, AL",ctry:"USA",region:"South",type:"Public",size:33000,setting:"suburban",net:18000,gpa:3.6,
     strengths:["Business","Engineering","Communications","Nursing","Education","Law"],v:{collab:.5,quirky:.35,idealist:.45,research:.6,spirit:.98,seminar:.25}},
    {n:"Texas A&M University",loc:"College Station, TX",ctry:"USA",region:"South",type:"Public",size:55000,setting:"suburban",net:16000,gpa:3.7,
     strengths:["Engineering","Agriculture","Business","Computer Science","Architecture","Veterinary Science"],v:{collab:.55,quirky:.35,idealist:.5,research:.7,spirit:.98,seminar:.2}},
    {n:"Virginia Tech",loc:"Blacksburg, VA",ctry:"USA",region:"South",type:"Public",size:30000,setting:"suburban",net:18000,gpa:3.8,
     strengths:["Engineering","Computer Science","Architecture","Business","Agriculture","Data Science"],v:{collab:.6,quirky:.5,idealist:.55,research:.7,spirit:.85,seminar:.3}},
    {n:"North Carolina State University",loc:"Raleigh, NC",ctry:"USA",region:"South",type:"Public",size:26000,setting:"urban",net:16000,gpa:3.7,
     strengths:["Engineering","Design","Agriculture","Computer Science","Textiles","Statistics"],v:{collab:.55,quirky:.5,idealist:.5,research:.75,spirit:.8,seminar:.3}},
    {n:"Clemson University",loc:"Clemson, SC",ctry:"USA",region:"South",type:"Public",size:21000,setting:"rural",net:18000,gpa:3.6,
     strengths:["Engineering","Business","Agriculture","Computer Science","Architecture","Nursing"],v:{collab:.55,quirky:.4,idealist:.5,research:.65,spirit:.95,seminar:.35}},
    {n:"Auburn University",loc:"Auburn, AL",ctry:"USA",region:"South",type:"Public",size:24000,setting:"suburban",net:18000,gpa:3.6,
     strengths:["Engineering","Business","Agriculture","Architecture","Veterinary Science","Nursing"],v:{collab:.55,quirky:.35,idealist:.5,research:.6,spirit:.95,seminar:.35}},
    {n:"Florida State University",loc:"Tallahassee, FL",ctry:"USA",region:"South",type:"Public",size:33000,setting:"urban",net:14000,gpa:3.7,
     strengths:["Business","Biology","Criminology","Psychology","Engineering","Theatre"],v:{collab:.55,quirky:.45,idealist:.55,research:.65,spirit:.9,seminar:.3}},
    {n:"University of South Carolina",loc:"Columbia, SC",ctry:"USA",region:"South",type:"Public",size:27000,setting:"urban",net:16000,gpa:3.6,
     strengths:["International Business","Business","Nursing","Engineering","Public Health","Hospitality"],v:{collab:.55,quirky:.4,idealist:.5,research:.6,spirit:.9,seminar:.3}},
    {n:"University of Tennessee",loc:"Knoxville, TN",ctry:"USA",region:"South",type:"Public",size:25000,setting:"urban",net:15000,gpa:3.6,
     strengths:["Engineering","Business","Agriculture","Nursing","Communications","Supply Chain"],v:{collab:.55,quirky:.4,idealist:.5,research:.65,spirit:.92,seminar:.3}},
    {n:"University of Massachusetts Amherst",loc:"Amherst, MA",ctry:"USA",region:"Northeast",type:"Public",size:24000,setting:"rural",net:20000,gpa:3.7,
     strengths:["Computer Science","Engineering","Business","Biology","Nursing","Linguistics"],v:{collab:.6,quirky:.6,idealist:.65,research:.75,spirit:.7,seminar:.3}},
    {n:"University of Connecticut",loc:"Storrs, CT",ctry:"USA",region:"Northeast",type:"Public",size:19000,setting:"rural",net:22000,gpa:3.6,
     strengths:["Business","Engineering","Nursing","Pharmacy","Biology","Education"],v:{collab:.55,quirky:.5,idealist:.55,research:.7,spirit:.85,seminar:.35}},
    {n:"Stony Brook University",loc:"Stony Brook, NY",ctry:"USA",region:"Northeast",type:"Public",size:17000,setting:"suburban",net:17000,gpa:3.7,
     strengths:["Computer Science","Engineering","Biology","Pre-Med","Physics","Mathematics"],v:{collab:.5,quirky:.65,idealist:.55,research:.85,spirit:.35,seminar:.3}},
    {n:"University of Iowa",loc:"Iowa City, IA",ctry:"USA",region:"Midwest",type:"Public",size:22000,setting:"urban",net:16000,gpa:3.6,
     strengths:["English","Nursing","Business","Engineering","Communications","Biology"],v:{collab:.6,quirky:.6,idealist:.6,research:.7,spirit:.85,seminar:.3}},
    {n:"Colorado School of Mines",loc:"Golden, CO",ctry:"USA",region:"West",type:"Public",size:5000,setting:"suburban",net:22000,gpa:3.8,
     strengths:["Engineering","Geology","Computer Science","Mining","Physics","Petroleum Engineering"],v:{collab:.6,quirky:.6,idealist:.45,research:.75,spirit:.5,seminar:.5}},
    {n:"University of Oregon",loc:"Eugene, OR",ctry:"USA",region:"West",type:"Public",size:19000,setting:"urban",net:18000,gpa:3.5,
     strengths:["Journalism","Business","Biology","Architecture","Psychology","Environmental Science"],v:{collab:.6,quirky:.6,idealist:.7,research:.6,spirit:.9,seminar:.3}},
    {n:"University of Arizona",loc:"Tucson, AZ",ctry:"USA",region:"West",type:"Public",size:35000,setting:"urban",net:15000,gpa:3.4,
     strengths:["Astronomy","Optics","Business","Engineering","Nursing","Computer Science"],v:{collab:.55,quirky:.55,idealist:.55,research:.75,spirit:.85,seminar:.25}},

    /* ---- tech, art & specialized ---- */
    {n:"Cooper Union",loc:"New York, NY",ctry:"USA",region:"Northeast",type:"Private",size:900,setting:"urban",net:22000,gpa:3.8,
     strengths:["Engineering","Art","Architecture","Design","Computer Science","Mechanical Engineering"],v:{collab:.6,quirky:.85,idealist:.6,research:.6,spirit:.2,seminar:.9}},
    {n:"Rose-Hulman Institute of Technology",loc:"Terre Haute, IN",ctry:"USA",region:"Midwest",type:"Private",size:2000,setting:"suburban",net:35000,gpa:3.8,
     strengths:["Engineering","Computer Science","Physics","Chemical Engineering","Mathematics","Robotics"],v:{collab:.8,quirky:.6,idealist:.45,research:.4,spirit:.5,seminar:.9}},
    {n:"Rhode Island School of Design",loc:"Providence, RI",ctry:"USA",region:"Northeast",type:"Private",size:2000,setting:"urban",net:35000,gpa:3.5,
     strengths:["Art","Design","Architecture","Illustration","Industrial Design","Animation"],v:{collab:.6,quirky:.95,idealist:.7,research:.3,spirit:.15,seminar:.85}},
    {n:"Berklee College of Music",loc:"Boston, MA",ctry:"USA",region:"Northeast",type:"Private",size:5000,setting:"urban",net:38000,gpa:3.3,
     strengths:["Music","Music Production","Songwriting","Film Scoring","Performance","Music Business"],v:{collab:.7,quirky:.85,idealist:.6,research:.2,spirit:.25,seminar:.7}},

    /* ---- additional HBCUs ---- */
    {n:"Morehouse College",loc:"Atlanta, GA",ctry:"USA",region:"South",type:"Private",size:2200,setting:"urban",net:22000,gpa:3.3,
     strengths:["Business","Political Science","Biology","Computer Science","Economics","Pre-Med"],v:{collab:.8,quirky:.5,idealist:.9,research:.5,spirit:.8,seminar:.7},flags:["hbcu"]},
    {n:"North Carolina A&T State University",loc:"Greensboro, NC",ctry:"USA",region:"South",type:"Public",size:12000,setting:"urban",net:12000,gpa:3.3,
     strengths:["Engineering","Business","Agriculture","Computer Science","Nursing","Biology"],v:{collab:.7,quirky:.4,idealist:.8,research:.6,spirit:.85,seminar:.4},flags:["hbcu"]},
    {n:"Hampton University",loc:"Hampton, VA",ctry:"USA",region:"South",type:"Private",size:3500,setting:"suburban",net:20000,gpa:3.3,
     strengths:["Business","Nursing","Engineering","Journalism","Biology","Pharmacy"],v:{collab:.75,quirky:.45,idealist:.85,research:.55,spirit:.8,seminar:.55},flags:["hbcu"]},
    {n:"Xavier University of Louisiana",loc:"New Orleans, LA",ctry:"USA",region:"South",type:"Private",size:3000,setting:"urban",net:18000,gpa:3.4,
     strengths:["Pharmacy","Pre-Med","Biology","Chemistry","Public Health","Psychology"],v:{collab:.8,quirky:.5,idealist:.85,research:.6,spirit:.6,seminar:.7},flags:["hbcu"]},

    /* ---- additional international ---- */
    {n:"University College London",loc:"London",ctry:"UK",region:"International",type:"Public",size:20000,setting:"urban",net:38000,gpa:3.85,
     strengths:["Engineering","Medicine","Economics","Architecture","Computer Science","Law"],v:{collab:.45,quirky:.65,idealist:.6,research:.9,spirit:.3,seminar:.45}},
    {n:"London School of Economics",loc:"London",ctry:"UK",region:"International",type:"Public",size:5000,setting:"urban",net:38000,gpa:3.85,
     strengths:["Economics","Political Science","Finance","International Relations","Law","Data Science"],v:{collab:.4,quirky:.6,idealist:.55,research:.85,spirit:.25,seminar:.5}},
    {n:"University of Edinburgh",loc:"Edinburgh",ctry:"UK",region:"International",type:"Public",size:25000,setting:"urban",net:32000,gpa:3.8,
     strengths:["Medicine","Computer Science","Engineering","Biology","Economics","Philosophy"],v:{collab:.5,quirky:.7,idealist:.65,research:.85,spirit:.4,seminar:.4}},
    {n:"King's College London",loc:"London",ctry:"UK",region:"International",type:"Public",size:22000,setting:"urban",net:35000,gpa:3.8,
     strengths:["Medicine","Law","International Relations","Nursing","Biology","War Studies"],v:{collab:.45,quirky:.6,idealist:.65,research:.85,spirit:.3,seminar:.45}},
    {n:"University of Manchester",loc:"Manchester",ctry:"UK",region:"International",type:"Public",size:28000,setting:"urban",net:30000,gpa:3.6,
     strengths:["Engineering","Computer Science","Business","Medicine","Physics","Economics"],v:{collab:.5,quirky:.6,idealist:.65,research:.8,spirit:.45,seminar:.35}},
    {n:"Nanyang Technological University",loc:"Singapore",ctry:"Singapore",region:"International",type:"Public",size:24000,setting:"suburban",net:18000,gpa:3.8,
     strengths:["Engineering","Computer Science","Business","Data Science","Communications","Materials Science"],v:{collab:.45,quirky:.5,idealist:.45,research:.85,spirit:.45,seminar:.3}},
    {n:"University of Hong Kong",loc:"Hong Kong",ctry:"Hong Kong",region:"International",type:"Public",size:18000,setting:"urban",net:22000,gpa:3.8,
     strengths:["Business","Medicine","Law","Engineering","Economics","Computer Science"],v:{collab:.4,quirky:.5,idealist:.5,research:.85,spirit:.4,seminar:.35}},
    {n:"Tsinghua University",loc:"Beijing",ctry:"China",region:"International",type:"Public",size:16000,setting:"urban",net:10000,gpa:3.95,
     strengths:["Engineering","Computer Science","Architecture","Economics","Physics","Data Science"],v:{collab:.35,quirky:.55,idealist:.45,research:.95,spirit:.4,seminar:.35}},
    {n:"University of Tokyo",loc:"Tokyo",ctry:"Japan",region:"International",type:"Public",size:14000,setting:"urban",net:12000,gpa:3.9,
     strengths:["Engineering","Physics","Economics","Medicine","Computer Science","Law"],v:{collab:.35,quirky:.6,idealist:.5,research:.95,spirit:.35,seminar:.4}},
    {n:"Seoul National University",loc:"Seoul",ctry:"South Korea",region:"International",type:"Public",size:17000,setting:"urban",net:10000,gpa:3.9,
     strengths:["Engineering","Business","Computer Science","Medicine","Economics","Physics"],v:{collab:.35,quirky:.55,idealist:.5,research:.92,spirit:.45,seminar:.35}},
    {n:"KAIST",loc:"Daejeon",ctry:"South Korea",region:"International",type:"Public",size:10000,setting:"suburban",net:10000,gpa:3.9,
     strengths:["Engineering","Computer Science","Physics","Robotics","Data Science","Biotechnology"],v:{collab:.5,quirky:.7,idealist:.45,research:.95,spirit:.3,seminar:.4}},
    {n:"University of Waterloo",loc:"Waterloo, ON",ctry:"Canada",region:"International",type:"Public",size:36000,setting:"suburban",net:28000,gpa:3.8,
     strengths:["Computer Science","Engineering","Mathematics","Data Science","Actuarial Science","Software Engineering"],v:{collab:.55,quirky:.65,idealist:.45,research:.7,spirit:.4,seminar:.3}},
    {n:"Australian National University",loc:"Canberra",ctry:"Australia",region:"International",type:"Public",size:18000,setting:"urban",net:28000,gpa:3.7,
     strengths:["Political Science","International Relations","Physics","Economics","Computer Science","Law"],v:{collab:.5,quirky:.65,idealist:.7,research:.88,spirit:.4,seminar:.4}},
    {n:"University of Sydney",loc:"Sydney",ctry:"Australia",region:"International",type:"Public",size:40000,setting:"urban",net:30000,gpa:3.7,
     strengths:["Business","Medicine","Engineering","Law","Architecture","Computer Science"],v:{collab:.5,quirky:.55,idealist:.65,research:.8,spirit:.5,seminar:.3}},
    {n:"Delft University of Technology",loc:"Delft",ctry:"Netherlands",region:"International",type:"Public",size:25000,setting:"urban",net:15000,gpa:3.8,
     strengths:["Engineering","Architecture","Computer Science","Aerospace","Industrial Design","Robotics"],v:{collab:.6,quirky:.65,idealist:.55,research:.85,spirit:.35,seminar:.4}},
    {n:"Technical University of Munich",loc:"Munich",ctry:"Germany",region:"International",type:"Public",size:45000,setting:"urban",net:5000,gpa:3.8,
     strengths:["Engineering","Computer Science","Physics","Data Science","Robotics","Management"],v:{collab:.5,quirky:.65,idealist:.5,research:.9,spirit:.3,seminar:.3}},
    {n:"Sciences Po",loc:"Paris",ctry:"France",region:"International",type:"Public",size:14000,setting:"urban",net:20000,gpa:3.8,
     strengths:["Political Science","International Relations","Economics","Law","Public Policy","Journalism"],v:{collab:.5,quirky:.7,idealist:.8,research:.75,spirit:.3,seminar:.7}}
  ];

  const ARCHES = [
    {id:"innovator",emo:"🚀",name:"The Innovator",desc:"Collaborative, tech-forward, build-stuff energy.",
     v:{collab:.8,quirky:.6,idealist:.4,research:.3,spirit:.5,seminar:.5}},
    {id:"scholar",emo:"📚",name:"The Scholar",desc:"Quirky, intellectual, deep-focus, research-driven.",
     v:{collab:.55,quirky:.95,idealist:.55,research:.9,spirit:.3,seminar:.85}},
    {id:"changer",emo:"🌍",name:"The Changemaker",desc:"Idealist, community-minded, interdisciplinary.",
     v:{collab:.85,quirky:.6,idealist:.95,research:.6,spirit:.45,seminar:.75}},
    {id:"traditionalist",emo:"🏟️",name:"The Traditionalist",desc:"School spirit, big network, active campus life.",
     v:{collab:.6,quirky:.35,idealist:.45,research:.55,spirit:.95,seminar:.3}}
  ];

  const SLIDERS = [
    {key:"collab",  left:"Hyper-competitive",            right:"Collaborative & supportive"},
    {key:"quirky",  left:"Work-hard, play-hard",          right:"Quirky & intellectual"},
    {key:"idealist",left:"Careerist / pre-professional",  right:"Idealist / mission-driven"},
    {key:"research",left:"Hands-on, project & co-op",      right:"Theory & research heavy"},
    {key:"spirit",  left:"Low-key sports scene",           right:"Huge school spirit"},
    {key:"seminar", left:"Big lectures & autonomy",        right:"Small seminars & mentorship"}
  ];

  const BACKGROUNDS = [
    {id:"hbcu",   label:"Interested in HBCUs"},
    {id:"women",  label:"Open to women's colleges"},
    {id:"firstgen",label:"First-generation"},
    {id:"intl",   label:"International student"}
  ];

  const REGIONS = ["Northeast","South","Midwest","West","International"];

  root.UM = root.UM || {};
  root.UM.data = { UNIS, ARCHES, SLIDERS, BACKGROUNDS, REGIONS };
})(typeof window !== "undefined" ? window : globalThis);
